### ISSUE TITLE
Named substitutions breaks in asciidoc-preview

### ISSUE THREAD

**Issue by rlopez133** [asciidoctor/atom-asciidoc-preview#102]
When using named substitutions , the output on the asciidoc preview fails to show the correct output.

Syntax:

````
Snippet of the `*ip -a*` command showing the network details.

[subs=+quotes]
----
# *ip -a*
[ ... Output Abbreviated ... ]
2: em1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP qlen 1000
    link/ether d4:be:d9:b3:8e:0f brd ff:ff:ff:ff:ff:ff
    inet 10.16.154.0/21 brd 10.16.159.255 scope global dynamic em1
       valid_lft 73367sec preferred_lft 73367sec
    inet6 fe80::d6be:d9ff:feb3:8e0f/64 scope link 
       valid_lft forever preferred_lft forever
[ ... Output Abbreviated ... ]
----
````

Output view from asciidoc-preview
![selection_010](https://cloud.githubusercontent.com/assets/8877333/9235604/4db8a2b6-4105-11e5-94f3-8b384a34cefe.png)

**Comment by lucascosti** [comment]
+1 for this issue

**Comment by mojavelinux** [comment]
It's probably not all named substitutions, but the quotes substitutions. My guess is that it's causing broken HTML to be generated. I'm not exactly sure what's going on, though.

**Comment by lucascosti** [comment]
yep, I was trying to use quotes when this happened.

**Comment by ldez** [comment]
Fix in the next version.
