### ISSUE TITLE
No syntax highlighting for certain macros

### ISSUE THREAD

**Issue by rlopez133** [asciidoctor/atom-asciidoc-preview#103]
There are specific macros that are not syntax highlighted that I wish were. I've tried playing with it myself but haven't had much luck. The only one I've successfully been able to do is a single inline comment block.

Below is a list of syntax I wish had some sort of highlighting. I'm providing an example if it takes a value. 

If you could provide some details in how the syntax highlighting is done, I could probably assist in some of these.

Regards,

Roger

````
1. //mycomment
2. [abstract] , [subs=+quotes] , any of the macros in a []
3. include::sample.adoc[]
4. If using an example block, the title of the block has no syntax highlighting. Example block:
./etc/resolv.conf
====
# Generated by NetworkManager + 
search sbu.lab.eng.bos.redhat.com + 
nameserver 10.16.36.29 + 
nameserver 10.11.5.19 + 
nameserver 10.5.30.160 + 
====

In this example block above './etc/resolv.conf' should be "white" to keep with your example block syntax highlighting.

5. Code blocks should be highlighted
----
# ip -a
-----
6. anchors, [[anchor]] 

7. NOTE, WARNING, CAUTION
````

**Comment by abelsromero** [comment]
Some time ago I found this link which explains the syntax language used. Maybe it can help you? 
http://manual.macromates.com/en/language_grammars.html

**Comment by rlopez133** [comment]
Thanks @abelsromero . I'll check it out!

**Comment by anthonny** [comment]
It should be an issue for the project https://github.com/asciidoctor/atom-language-asciidoc, no?

**Comment by mojavelinux** [comment]
@anthonny yes.

**Comment by Mogztter** [comment]
@rlopez133 Did you check out the latest version of https://github.com/asciidoctor/atom-language-asciidoc ? I think most of your examples are now properly highlighted ?

**Comment by mojavelinux** [comment]
I'm going to close this issue since it a) pertains to https://github.com/asciidoctor/atom-language-asciidoc and b) is being addressed there. If there are specific examples that don't work, please file new issues in that repository. Thanks!
