### ISSUE TITLE
The preview text is hard to read because it is light grey

### ISSUE THREAD

**Issue by rocketraman** [asciidoctor/atom-asciidoc-preview#105]
The preview text is hard to read because it is a light grey color (`rgb(170, 170, 170)` or `#aaaaaa`).

The offending style seems to come from `/usr/share/atom/resources/app.asar/static/atom.less` and is named `atom-workspace`.

**Comment by mojavelinux** [comment]
The body text should be:

```
color: rgba(0,0,0,.8);
```

Perhaps the default stylesheet is not passing on this setting in the Atom environment....

Yep, the problem is that when the styles are wrapped, it's trying to style the following selector:

```
.asciidoc-preview body
```

That needs to be fixed so that the body styles are applied directly to .asciidoc-preview. See the stylesheet in this repository.

**Comment by rocketraman** [comment]
> That needs to be fixed so that the body styles are applied directly to .asciidoc-preview. See the stylesheet in this repository.

Where does it need to be fixed?

**Comment by mojavelinux** [comment]
Here:

https://github.com/asciidoctor/atom-asciidoc-preview/blob/master/styles/asciidoc-preview.less#L155

But the real (long-term fix) is here:

https://github.com/asciidoctor/asciidoctor-stylesheet-factory/issues/18

**Comment by lucascosti** [comment]
+1 for this issue

**Comment by Xaviju** [comment]
+1 Can't read.

Thanks!

**Comment by anthonny** [comment]
Hi,
A quick workaround, in the Atom editor, open the command palette (**Ctrl+Shift+P** / **Cmd+Shift+P**) and type **your stylesheet**.
![image](https://cloud.githubusercontent.com/assets/2006548/10791396/943fd3f2-7d88-11e5-8f34-395a3af6a74e.png)

A tab named **style.less** will be open, at the end of the file add this : 

```less
atom-workspace {
 .asciidoc-preview {
   color: #000;
 }
}
```
I'll do my best to fix this bug soon.

**Comment by mojavelinux** [comment]
@anthonny I still think that the text should be `rgba(0,0,0,0.8)` (equivalent to 333333) instead of `#000`. I'd also be okay with `rgba(0,0,0,0.865)` (equivalent to 222222).

**Comment by rocketraman** [comment]
@anthonny Thank you, the workaround works (after a restart of Atom).

@mojavelinux I agree, rgba(0,0,0,0.8) definitely looks better than `#000`.
