### ISSUE TITLE
Spacing between text and URLs is often too small

### ISSUE THREAD

**Issue by rocketraman** [asciidoctor/atom-asciidoc-preview#106]
The spacing between text and URLs is often too small -- it actually looks as if there is no space at all.

My platform is Fedora Linux 20 and I am on Atom 1.0.8.

Here is an example:

![image](https://cloud.githubusercontent.com/assets/53049/9568689/e8309b1a-4f1e-11e5-8a88-2e7f433c9a59.png)

The Asciidoc source of the above image is:

```
The client is best debugged via browser developer tools.

The server can be debugged and profiled using
https://github.com/node-inspector/node-inspector[node-inspector].
```

(In the above there is indeed a hard return after "using" but removing that makes no difference).

**Comment by abelsromero** [comment]
Hi,

I'm not experiencing this issue.
To get more information, if you press ctrl+alt+i you load the chrome dev tools. With those, you can inspect the preview tab and see the generated HTML. Can you post what HTML are you getting?
When I write it in a single line, I get a space.
```
<div class="paragraph">
<p>The server can be debugged and profiled using <a href="https://github.com/node-inspector/node-inspector">node-inspector</a>.</p>
</div>
```

> (In the above there is indeed a hard return after "using" but removing that makes no difference).

This is intended, all lines will be combined in a single paragraph. In order to create a line break, you either have to use the `+` or just create a new paragraph using two line breaks.
Check this for more info http://asciidoctor.org/docs/asciidoc-writers-guide/#wrapped-text-and-hard-line-breaks.
As a personal note, writting each sentence in a single line is a bit odd at the beginning. But once you get used to it, you can't go back. It's really usefull and helps to see how many concepts you have in a pagraph, also allows you to move lines up and down with shortcuts to reorganize concepts.

**Comment by rocketraman** [comment]
> Can you post what HTML are you getting?

I don't see any problem with the generated HTML. It seems to be a rendering issue. Perhaps fonts? It's weird, I don't have this problem anywhere else.

![image](https://cloud.githubusercontent.com/assets/53049/9570303/b1ba8500-4f55-11e5-9d9f-2eb84a9f90d9.png)

> This is intended, all lines will be combined in a single paragraph

Yes, I'm aware of that, I was just pointing out that whatever the bug is, it wasn't related to the hard return (and I wouldn't have expected it to be). I just thought maybe it was affecting the rendering somehow.

**Comment by rocketraman** [comment]
If I right-click and do "Edit as HTML" it looks better:

```
<div class="paragraph">
<p>The server can be debugged and profiled using
<a href="https://github.com/node-inspector/node-inspector">node-inspector</a>.</p>
</div>
```

Perhaps a font issue? I don't have this problem anywhere else.

**Comment by abelsromero** [comment]
The HTML seems normal, is the same I get when using a line break.

> Perhaps a font issue?

I am thinking of maybe another atom plugin adding some style to links.
Manually, I've been able to change the CSS to remove margins to get the same result. But other than that i haven't been able to reproduce the issue :/

**Comment by rocketraman** [comment]
I think I see the problem...  asciidoc-preview is setting the following style:

```css
.asciidoc-preview p, .asciidoc-preview td.content {
  letter-spacing: -0.01em;
}
```

See:

![image](https://cloud.githubusercontent.com/assets/53049/9585125/e426ba08-4fe2-11e5-96a2-9dba4fd62f3c.png)

If I disable the letter-spacing style in the inspector, the output is correct:

![image](https://cloud.githubusercontent.com/assets/53049/9585143/02339dd6-4fe3-11e5-8f7b-0a5820bf1c07.png)

I think the source is here: https://github.com/asciidoctor/atom-asciidoc-preview/blob/64a7c7c08b06477489c6d1366b671fd6f93b80b0/styles/asciidoc-preview.less#L472

**Comment by mojavelinux** [comment]
I'm very surprised that letter-spacing value is causing the space in front of the link to collapse. That looks like a Webkit bug. Regardless, we could remove that in the styles as that's a pretty minor style. Can anyone else confirm this behavior?

**Comment by rocketraman** [comment]
> I'm very surprised that letter-spacing value is causing the space in front of the link to collapse.

Yeah, its odd. Leaving the `letter-spacing` setting as-is, and setting a `word-spacing` style to an explicit value "fixes" the problem as well. However, if `word-spacing` is set to `normal`, it does not.

**Comment by mojavelinux** [comment]
What value works for word-spacing? Once we get that clarified, I'm happy with adding this "hack".

**Comment by rocketraman** [comment]
Hmm, actually I seem to have spoken too soon. It seems to vary -- for some values of word-spacing it works, and other values it does not, so that doesn't appear to be a reliable solution. For example, here it is with 1em:

![image](https://cloud.githubusercontent.com/assets/53049/9589567/46e683b6-4ffd-11e5-8ff9-bf374a02b298.png)

Clearly, the renderer does not think that it is separating words there.

The HTML is:

```html
<p>The server can be debugged and profiled using
<a href="https://github.com/node-inspector/node-inspector">node-inspector</a>.</p>
```

(hard wrap)

but if I edit it to:

```html
<p>The server can be debugged and profiled using <a href="https://github.com/node-inspector/node-inspector">node-inspector</a>.</p>
```

(no hard returns)

Then it renders fine. And I see that this can be done by removing the hard return in the source Asciidoc file as well. Which, as I understand Asciidoc, should not cause the output to change because of the wrapping / hard break rules.

**Comment by rocketraman** [comment]
> Then it renders fine. And I see that this can be done by removing the hard return in the source Asciidoc file as well. Which, as I understand Asciidoc, should not cause the output to change because of the wrapping / hard break rules.

Actually, spoke too soon again -- it only works with no hard wrap *and* the `word-spacing` css. With either of the preceding conditions not met, it has no spacing. It looks like removing letter-spacing is the only reliable solution. Strange!

**Comment by ldez** [comment]
Can you provide your package list?

Execute the following command:
`apm list`

**Comment by rocketraman** [comment]
@ldez The package list is currently:

```
/home/raman/.atom/packages (10)
├── api-workbench@0.8.28
├── asciidoc-preview@2.2.3
├── atomic-chrome@0.3.0
├── editorconfig@1.4.1
├── git-diff-details@1.1.0
├── git-log@0.4.1
├── git-time-machine@1.5.3
├── language-asciidoc@1.4.8
├── linter@1.11.4
└── merge-conflicts@1.4.3
```

I actually can't replicate the issue with this version of Atom and the plugin.

**Comment by lucascosti** [comment]
> I actually can't replicate the issue with this version of Atom and the plugin.

+1; I think this issue has been fixed somewhere along the way.

**Comment by rocketraman** [comment]
With the confirmation from @lucascosti I'll close this! Thanks!
