### ISSUE TITLE
can't install success with atom

### ISSUE THREAD

**Issue by NancyZY** [asciidoctor/atom-asciidoc-preview#107]
![1](https://cloud.githubusercontent.com/assets/9473445/9872447/01900c3a-5bcc-11e5-8605-6b7732fc5be5.png)

**Comment by abelsromero** [comment]
The error does not really say much to me, but could it be that you're behind a proxy?

**Comment by NancyZY** [comment]
Thank you for your reply so quickly，I try to close proxy, but it seems doesn't work

**Comment by Mogztter** [comment]
I think this is a network error (`stack Error: read ECONNRESET`).
Could you try to install another package ? If this is working, could you please run your command with `--verbose` flag ?

**Comment by ldez** [comment]
It's a possible node-gyp problem

**Comment by ldez** [comment]
@NancyZY can you try with 1.0.4?
