### ISSUE TITLE
preview crashes with ifeval

### ISSUE THREAD

**Issue by everflux** [asciidoctor/atom-asciidoc-preview#108]
I have a document like this

```
ifeval::["{backend}" == "pdf"]
== Note on PDF output
...
```

It causes the preview to not refresh/crash.

**Comment by mojavelinux** [comment]
I wonder if this is something that traces back to Asciidoctor.js. It kind of seems like it. If so, it might be best to address it there where we can add a test. It would also mean it affects all uses of Asciidoctor.js. If it's specific to Atom, then we can keep it here.

(You can test if it's Asciidoctor.js by trying the [asciidoctor-cli](https://www.npmjs.com/package/asciidoctor-cli).

**Comment by mojavelinux** [comment]
It seems to work find for me. Are you closing the conditional, by chance?

**Comment by mojavelinux** [comment]
Actually, now I'm seeing this behavior in Atom after I upgrade the package. But I can't quite figure out what the scenario is that triggers it precisely.

**Comment by mojavelinux** [comment]
Aha! I know what it is. I think we've hit this before in Asciidoctor.js. The ifeval comparison passed through `==` and `!=` to the underlying objects. In the JavaScript environment, String does not respond to these methods, so it hits an exception. So this is an Asciidoctor.js issue.

See https://github.com/opal/opal/issues/970

I think this is solved once Asciidoctor.js upgrades to Opal 0.8.0 (though we should still probably add a test). I also fixed this in the upcoming Asciidoctor 1.5.3.

https://github.com/asciidoctor/asciidoctor.js/pull/118
