### ISSUE TITLE
Mention right-click options in README

### ISSUE THREAD

**Issue by Xcodo** [asciidoctor/atom-asciidoc-preview#109]
It would be good to highlight in the README file that there are some fairly useful options in the right-click menu in a preview. I only found them because I was looking through some of the issues out of nosiness and saw it mentioned.

**Comment by leif81** [comment]
Wow, I didn't realize these options until now. :+1:

**Comment by mojavelinux** [comment]
:+1:

**Comment by Xcodo** [comment]
I went to add a simple sentence about the right-slick menu to the README, but I wondered if an updated screenshot showing the preview in action would be good. I've got a GIF that's 330 kB, probably too big to want to carry around in the repo, but I'll drop it in here and link to that for the PR...
![atom-asciidoc-preview-demo](https://cloud.githubusercontent.com/assets/6715247/11607696/0f555d54-9b49-11e5-8c72-31b718289562.gif)

**Comment by mojavelinux** [comment]
I like it! I don't think 330KB is a problem.

**Comment by Mogztter** [comment]
I think we can close this issue ?

**Comment by Xcodo** [comment]
Yes, was fixed in #114.
