### ISSUE TITLE
Unable to install on Atom 1.3.2 running on windows 10

### ISSUE THREAD

**Issue by antobar** [asciidoctor/atom-asciidoc-preview#116]
Installation through settings->Install fails with the following message

npm WARN deprecated CSSselect@0.4.1: the module is now available as 'css-select'
npm WARN deprecated CSSwhat@0.4.7: the module is now available as 'css-what'
npm WARN addRemoteGit Error: Command failed: 
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:658:15)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:98:17)
npm WARN addRemoteGit     at maybeClose (child_process.js:766:16)
npm WARN addRemoteGit     at Process.ChildProcess._handle.onexit (child_process.js:833:5)
npm WARN addRemoteGit  git://github.com/anthonny/opal-npm-wrapper.git#0.1.1 resetting remote C:\Users\TTT\.atom\.apm\_git-remotes\git-github-com-anthonny-opal-npm-wrapper-git-1727a7b3 because of error: { [Error: Command failed: ] killed: false, code: 1, signal: null }
npm ERR! git clone --template=C:\Users\TTT\.atom\.apm\_git-remotes\_templates --mirror git://github.com/anthonny/opal-npm-wrapper.git C:\Users\TTT\.atom\.apm\_git-remotes\git-github-com-anthonny-opal-npm-wrapper-git-1727a7b3: Cloning into bare repository 'C:\Users\TTT\.atom\.apm\_git-remotes\git-github-com-anthonny-opal-npm-wrapper-git-1727a7b3'...
npm ERR! git clone --template=C:\Users\TTT\.atom\.apm\_git-remotes\_templates --mirror git://github.com/anthonny/opal-npm-wrapper.git C:\Users\TTT\.atom\.apm\_git-remotes\git-github-com-anthonny-opal-npm-wrapper-git-1727a7b3: fatal: unable to connect to github.com:
npm ERR! git clone --template=C:\Users\TTT\.atom\.apm\_git-remotes\_templates --mirror git://github.com/anthonny/opal-npm-wrapper.git C:\Users\TTT\.atom\.apm\_git-remotes\git-github-com-anthonny-opal-npm-wrapper-git-1727a7b3: github.com[0: 192.30.252.131]: errno=No error
npm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\\Users\\TTT\\AppData\\Local\\atom\\app-1.3.2\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\TTT\\AppData\\Local\\atom\\app-1.3.2\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\TTT\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\TTT\\.atom\\.apmrc" "install" "C:\\Users\\AC460~1.LJU\\AppData\\Local\\Temp\\d-1151122-11528-10jdkth\\package.tgz" "--target=0.34.3" "--arch=ia32" "--msvs_version=2013"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code 128

npm ERR! Command failed: Cloning into bare repository 'C:\Users\TTT\.atom\.apm\_git-remotes\git-github-com-anthonny-opal-npm-wrapper-git-1727a7b3'...
npm ERR! fatal: unable to connect to github.com:
npm ERR! github.com[0: 192.30.252.131]: errno=No error
npm ERR! 
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

**Comment by ldez** [comment]
Can you retry with the 1.0.0 ?

**Comment by ldez** [comment]
Fixed in 1.0.0
