### ISSUE TITLE
Rendering of preview is cut off and stops mid-file

### ISSUE THREAD

**Issue by simonbasle** [asciidoctor/atom-asciidoc-preview#120]
When writing a long document, I noticed that at some point the rendering of the Asciidoc stopped. "normal" text is just cut, as seen in this screenshot:
![image](https://cloud.githubusercontent.com/assets/6986166/12725871/108ad740-c915-11e5-80f6-abc5e6368986.png)

Note that if I have source listings, these get rendered (and syntax highlighted). Note also that if I open the developer tools in Atom, the problem seems to disappear (and no particular error is shown).
Any idea what might be going on? :(

**Comment by ldez** [comment]
Can you retry with the 1.0.0 ?

**Comment by simonbasle** [comment]
just tested with 1.0.1 and a large document, the problem seems to have disappeared 👍

**Comment by ldez** [comment]
Thanks, now I can close this issue.
