### ISSUE TITLE
Unicode ids are broken

### ISSUE THREAD

**Issue by andya9** [asciidoctor/atom-asciidoc-preview#121]
If I have: `[[ā]]` the preview shows a literal `[[ā]]` instead of transforming it into an id

**Comment by mojavelinux** [comment]
Please see https://github.com/asciidoctor/asciidoctor.js/issues/43. This is a limitation of the JavaScript regexp engine. The solution is to "ugprade" the regexp engine in JavaScript using XRegExp.

**Comment by andya9** [comment]
thank’you very much for pointing it out!

**Comment by mojavelinux** [comment]
@ldez actually, I would mark this as "upstream" instead of "declined" since the change has to be in Asciidoctor.js. Same outcome, but just more accurate labeling, IMO.

**Comment by ldez** [comment]
done! :wink:
