### ISSUE TITLE
[feature request] tree-view of headers for quick navigation

### ISSUE THREAD

**Issue by flyisland** [asciidoctor/atom-asciidoc-preview#126]
something like https://github.com/xndcn/symbols-tree-view for asciidoc, although this feature is often used by program languages, but I do think it would be very useful while editing long article.

**Comment by mojavelinux** [comment]
I agree. However, I think this is a duplicate of #9 (in other words, we definitely agree)

**Comment by flyisland** [comment]
got it, subscribe #9 now.
