### ISSUE TITLE
Save As HTML... : no Table of Contents in the final file!

### ISSUE THREAD

**Issue by usermail** [asciidoctor/atom-asciidoc-preview#128]
I'm new to asciidoc, Asciidoctor on Ruby doesn't work properly in my installation. 
So I want to just use HTML preview to create files but then i loose Table of Contents. I solved this by removing `<style>...</style>` in 'templates/default.html' and replacing it with `<link href="css/style.css" rel="stylesheet">` instead. 
Then I can put my own 'css/style.css' file, like this https://github.com/usermail/usermail.github.io

I wonder if this ability will disappear when asciidoc package get updated in Atom? 

Also having styles embedded in html is all right when creating one single file, but it's not very good for building a website. Otherwise I'm quite impressed with asciidoc!

**Comment by mojavelinux** [comment]
Please see the Asciidoctor User Manual for how to control both the ToC and the inlining of CSS.

* http://asciidoctor.org/docs/user-manual/#using-a-toc-with-embeddable-html
* http://asciidoctor.org/docs/user-manual/#styling-the-html-with-css

**Comment by ldez** [comment]
See the package settings:
![capture du 2016-06-06 02-41-39](https://cloud.githubusercontent.com/assets/5674651/15809379/3bf4d8c6-2b90-11e6-838f-52d60c44eb1d.png)
