### ISSUE TITLE
Suggestion popup for attributes contains unset attributes as well

### ISSUE THREAD

**Issue by ygra** [asciidoctor/atom-asciidoc-preview#131]
E.g. for the following code:

    :attr:
    :attr!:

starting to type `{` will offer both `attr` and `attr!` in the suggestion list, despite `attr` no longer existing (things seem to be correct in that it doesn't appear in the list *prior* to setting the attribute) and `attr!` never having been an attribute to begin with.

**Comment by ldez** [comment]
Since 1.0.0, the autocompletions have been migrated to a new package: [autocomplete-asciidoc](https://atom.io/packages/autocomplete-asciidoc)

This issue is fixed in the new package.
