### ISSUE TITLE
[discrete] section under toc::[] setting appears before TOC in preview

### ISSUE THREAD

**Issue by chuckf** [asciidoctor/atom-asciidoc-preview#137]
When using the [discrete] attribute on a section heading following a toc::[] setting for a TOC using the macro setting in the header, the section flagged as discrete appears before the TOC in the preview. The document is rendered as expected from the CLI.

Displays Section 2 as expected on preview:

```
= This is a discrete tag test
:toc: macro

[discrete]
== Section 1

This is text in the first section

toc::[]

== Section 2

This is text in the second section.

== Section 3

This is text in the third section.
```

Displays Section 2 in the wrong place on preview:

```
= This is a discrete tag test
:toc: macro

[discrete]
== Section 1

This is text in the first section

toc::[]

[discrete]
== Section 2

This is text in the second section.

== Section 3

This is text in the third section.
```

**Comment by mojavelinux** [comment]
I'm not sure I understand. I think that the discrete heading should appear before the TOC because it comes before the TOC in the document order.

Perhaps if you added some screenshots of the output you are getting, the problem will be more clear.

**Comment by chuckf** [comment]
Here are the screenshots using the two different sections of code I posted in the original issue. The filenames refer to Section 2 with or without the discrete tags.

![with_discrete_tag](https://cloud.githubusercontent.com/assets/3385499/15343051/a8fd7b22-1c67-11e6-9528-983d72398037.png)
![without_discrete_tag](https://cloud.githubusercontent.com/assets/3385499/15343052/a8fe8116-1c67-11e6-91cc-99c56d41b779.png)

**Comment by mojavelinux** [comment]
@chuckf what's happening is that your setting for the plugin is overriding the value of the toc attribute in your document. The behavior you are observing is consistent with the preamble placement of the toc. 

You must have "preamble" set in the Table of Contents field of the preview plugin in your settings.

**Comment by chuckf** [comment]
The "preamble" setting in the plugin was indeed the culprit. I wasn't expecting there to be such a setting. Thanks for the information.

**Comment by mojavelinux** [comment]
:+1: 

I definitely think some refinement is still needed in how the toc is handled by the plugin.

**Comment by ldez** [comment]
in #153, add option explanations and rename the options.
