### ISSUE TITLE
Add Atom package url to the header.

### ISSUE THREAD

**Issue by ldez** [asciidoctor/atom-asciidoc-preview#141]
currently:
![capture du 2016-05-22 18-00-15](https://cloud.githubusercontent.com/assets/5674651/15454981/1d154d7c-2047-11e6-9c4f-4a50157a5fef.png)

The language package:

![capture du 2016-05-22 18-01-01](https://cloud.githubusercontent.com/assets/5674651/15454986/2e640da2-2047-11e6-8425-bc31a44a4bac.png)

**Comment by Mogztter** [comment]
:+1:
We could also add the Atom icon ;)

**Comment by Mogztter** [comment]
@mojavelinux I think I don't have the right to modify the text. Could you please do it ?

**Comment by mojavelinux** [comment]
Done!
