### ISSUE TITLE
Release 0.7.0 before remove autocomplete

### ISSUE THREAD

**Issue by ldez** [asciidoctor/atom-asciidoc-preview#142]
the last release is in dec. 2015, many bugs are fixed now.

**Comment by Mogztter** [comment]
Do I have the right to do it ? (I've never released an Atom package before)

**Comment by ldez** [comment]
Yes :wink:

How to publish an Atom package ?

- have a write access on the Github repository.
- have an Atom account.

I going to create a contributors documentation for this package.

**Comment by mojavelinux** [comment]
@Mogztter It's pretty much the same as npm publish, except you type apm. @ldez is well seasoned in the process at this point. You have write access through the atom-package-committers team.

**Comment by ldez** [comment]
- clone in a specific directory the repo to have 'origin' link with this repository.
- `apm login` (optional)
- `apm publish patch` or `apm publish minor` or `apm publish major`

I will doing this release for this time.

**Comment by ldez** [comment]
Done!

**Comment by mojavelinux** [comment]
I'm really looking forward to having automated releases for this plugin as well. That should really help to revive the user base.

**Comment by anthonny** [comment]
@mojavelinux I agree but i think that we must work on tests before ;)

**Comment by ldez** [comment]
yes, exactly as I did for `language-asciidoc` :smile:
