### ISSUE TITLE
Atom's preview link is broken in 0.8.0

### ISSUE THREAD

**Issue by chuckf** [asciidoctor/atom-asciidoc-preview#143]
When clicking on Packages > Asciidoc Preview the option to Toggle Preview shows the text on one line then the keyboard shortcut on the next. 

When the Toggle Preview text is clicked, the preview window does not open.

When the keyboard shortcut is clicked, the preview window displays as expected. 

This was found on [two different] Mac OS X El Capitan, Atom 1.7.4, and atom-asciidoc-preview 0.8.0. 

![preview_toggle_menu](https://cloud.githubusercontent.com/assets/3385499/15511187/8851074a-21a8-11e6-8c0b-26d3e7f17e14.png)

**Comment by ldez** [comment]
Fixed in 0.8.1
