### ISSUE TITLE
Unable to install on Atom 1.7.4 running on windows 10

### ISSUE THREAD

**Issue by theltemes** [asciidoctor/atom-asciidoc-preview#150]
## Description

Unable to install from command line or package manager.

[asciidoc-preview-log.txt](https://github.com/asciidoctor/atom-asciidoc-preview/files/285023/asciidoc-preview-log.txt)

**Comment by ldez** [comment]
Can you list your packages ?

```shell
apm list
```

**Comment by ldez** [comment]
it's a fresh install or an update ?

**Comment by theltemes** [comment]
Fresh Install

[36mBuilt-in Atom Packages[39m (89)
├── about@1.4.2
├── archive-view@0.61.1
├── atom-dark-syntax@0.27.0
├── atom-dark-ui@0.51.0
├── atom-light-syntax@0.28.0
├── atom-light-ui@0.43.0
├── autocomplete-atom-api@0.10.0
├── autocomplete-css@0.11.0
├── autocomplete-html@0.7.2
├── autocomplete-plus@2.29.1
├── autocomplete-snippets@1.10.0
├── autoflow@0.27.0
├── autosave@0.23.1
├── background-tips@0.26.0
├── base16-tomorrow-dark-theme@1.1.0
├── base16-tomorrow-light-theme@1.1.1
├── bookmarks@0.38.2
├── bracket-matcher@0.81.0
├── command-palette@0.38.0
├── deprecation-cop@0.54.1
├── dev-live-reload@0.47.0
├── encoding-selector@0.21.0
├── exception-reporting@0.37.0
├── find-and-replace@0.199.0
├── fuzzy-finder@1.0.5
├── git-diff@1.0.1
├── go-to-line@0.30.0
├── grammar-selector@0.48.1
├── image-view@0.57.0
├── incompatible-packages@0.25.1
├── keybinding-resolver@0.35.0
├── language-c@0.51.1
├── language-clojure@0.20.0
├── language-coffee-script@0.46.1
├── language-csharp@0.12.0
├── language-css@0.36.0
├── language-gfm@0.85.0
├── language-git@0.12.1
├── language-go@0.42.0
├── language-html@0.44.1
├── language-hyperlink@0.16.0
├── language-java@0.17.0
├── language-javascript@0.110.0
├── language-json@0.17.6
├── language-less@0.29.0
├── language-make@0.21.0
├── language-mustache@0.13.0
├── language-objective-c@0.15.1
├── language-perl@0.32.0
├── language-php@0.37.0
├── language-property-list@0.8.0
├── language-python@0.43.0
├── language-ruby@0.68.3
├── language-ruby-on-rails@0.25.0
├── language-sass@0.46.0
├── language-shellscript@0.21.0
├── language-source@0.9.0
├── language-sql@0.20.0
├── language-text@0.7.1
├── language-todo@0.27.0
├── language-toml@0.18.0
├── language-xml@0.34.4
├── language-yaml@0.25.1
├── line-ending-selector@0.3.1
├── link@0.31.1
├── markdown-preview@0.158.0
├── metrics@0.53.1
├── notifications@0.63.1
├── one-dark-syntax@1.2.0
├── one-dark-ui@1.2.0
├── one-light-syntax@1.2.0
├── one-light-ui@1.2.0
├── open-on-github@1.0.1
├── package-generator@1.0.0
├── settings-view@0.235.1
├── snippets@1.0.1
├── solarized-dark-syntax@1.0.0
├── solarized-light-syntax@1.0.0
├── spell-check@0.67.0
├── status-bar@1.1.2
├── styleguide@0.45.2
├── symbols-view@0.112.0
├── tabs@0.96.0
├── timecop@0.33.1
├── tree-view@0.205.0
├── update-package-dependencies@0.10.0
├── welcome@0.34.0
├── whitespace@0.32.2
└── wrap-guide@0.38.1

[36mCommunity Packages (4)[39m C:\Users\thelt\.atom\packages
├── asciidoc-assistant@0.2.0
├── asciidoc-image-helper@0.9.4
├── autocomplete-asciidoc@0.1.1
└── language-asciidoc@1.4.5

└── (empty)

---
Thad Heltemes, Ph.D.

http://theltemes.net

On Thu, May 26, 2016 at 1:20 PM, Ludovic Fernandez <notifications@github.com

**Comment by ldez** [comment]
Have you installed from the assistant package or via GUI or via CLI ?

**Comment by theltemes** [comment]
Yes, and they both fail with the same error.

**Comment by ldez** [comment]
I think it's an issue with Highlight library: https://github.com/atom/highlights/issues/36

**Comment by ldez** [comment]
I will fixed this, but you can use a workaround (it's complex but if you want):

1. Check that python is in your path by writting `python --version` in the console. 
    1. If not then download [python 2.7](https://www.python.org/ftp/python/2.7.11/python-2.7.11.amd64.msi)
2. Download [Microsoft Visual C++ Build Tools 2015 Technical Preview](http://go.microsoft.com/fwlink/?LinkId=691126)
3. do `apm config -g set msvs_version 2015`
4. do `apm install asciidoc-preview`

**Comment by ldez** [comment]
Related to #63

I will created a release very soon.

**Comment by ldez** [comment]
new version will be here very soon: 10 minutes

**Comment by ldez** [comment]
can you try with the new 1.0.3 version ?

**Comment by theltemes** [comment]
C:\Users\thelt>apm i asciidoc-preview@1.0.3
Installing asciidoc-preview@1.0.3 to C:\Users\thelt\.atom\packages failed

> oniguruma@5.1.2 install C:\Users\thelt\AppData\Local\Temp\apm-install-dir-116426-15164-1c1sx\node_modules\asciidoc-preview\node_modules\highlights\node_modules\first-mate\node_modules\oniguruma
> node-gyp rebuild


C:\Users\thelt\AppData\Local\Temp\apm-install-dir-116426-15164-1c1sx\node_modules\asciidoc-preview\node_modules\highlights\node_modules\first-mate\node_modules\oniguruma>if not defined npm_config_node_gyp (node "C:\Users\thelt\AppData\Local\atom\app-1.7.4\resources\app\apm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )

npm WARN engine escodegen@1.8.0: wanted: {"node":">=0.12.0"} (current: {"node":"0.10.40","npm":"2.13.3"})
gypnpm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\\Users\\thelt\\AppData\\Local\\atom\\app-1.7.4\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\thelt\\AppData\\Local\\atom\\app-1.7.4\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\thelt\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\thelt\\.atom\\.apmrc" "install" "C:\\Users\\thelt\\AppData\\Local\\Temp\\d-116426-15164-vawv4r\\package.tgz" "--target=0.36.8" "--arch=ia32"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! oniguruma@5.1.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the oniguruma@5.1.2 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the oniguruma package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls oniguruma
npm ERR! There is likely additional logging output above.

**Comment by ldez** [comment]
do `apm rebuild-module-cache` please.

**Comment by theltemes** [comment]
Same result.

**Comment by ldez** [comment]
oh I know, I missed a line... sorry.

version 1.0.4 coming soon.

**Comment by ldez** [comment]
Can you try with version 1.0.4?

**Comment by theltemes** [comment]
That worked. Thanks.

**Comment by ldez** [comment]
:sweat: :smile:
