### ISSUE TITLE
"Toggle" should be replaced by "Enable" or "Disable" depending on the state

### ISSUE THREAD

**Issue by Mogztter** [asciidoctor/atom-asciidoc-preview#163]
## Description

I don't know if this is just me but sometime I don't really remember the state of front matter or compat mode. 
Is it possible to change the label depending on the state ? When compat mode is enabled, the menu should be "Disable compat mode" and vice-versa.

## Screenshots

.What is the state?!
![cc769042-27a3-11e6-9f01-c9aee699acd0](https://cloud.githubusercontent.com/assets/333276/15723972/3b8fea7c-2845-11e6-9202-e8c82a21d10c.png)

**Comment by ldez** [comment]
The menu is hard coded.
All Atom's package work like that.

**Comment by ldez** [comment]
To know the state, you must open 'Settings' page.

**Comment by ldez** [comment]
I must decline this issue.

**Comment by Mogztter** [comment]
> The menu is hard coded.

Too bad :disappointed: 

> I must decline this issue.

No problem
