### ISSUE TITLE
Support "Save As PDF..."

### ISSUE THREAD

**Issue by netzwerg** [asciidoctor/atom-asciidoc-preview#167]
First and foremost: I love your package, thank you for the great work!

Only recently I noticed the "Save As HTML..." action, which comes in very handy. Any plans to support "Save As PDF..." as well? Would be greatly appreciated!

**Comment by mojavelinux** [comment]
Anyone know if Electron gives us access to the Print to PDF feature of WebKit? If so, I recommend going that route.

If you are looking for a similar shell to Atom that offers integration with the Asciidoctor toolchain, I recommend checking out [AsciidocFX](http://asciidocfx.com/). The two projects draw ideas from each other.

**Comment by netzwerg** [comment]
I am used to converting my documents through the [asciidoctor-gradle-plugin](https://github.com/asciidoctor/asciidoctor-gradle-plugin), which gives very nice PDFs. AsciidocFX doesn't produce the same style (I just asked @rahmanusta on [Gitter](https://gitter.im/asciidocfx/AsciidocFX?at=57512563f44fde236e530e35): they don't use the asciidoctor-pdf project).

Essentially, I am looking for a light-weight alternative to quickly generate a nice looking PDF without setting up a Gradle project.

**Comment by ldez** [comment]
Atom doesn't support the 'Print to PDF' feature of WebKit.
Some packages have trying to do that but with a poor answer.

The better solution seems to create a binding to [asciidoctor-pdf](https://github.com/asciidoctor/asciidoctor-pdf).

**Comment by mojavelinux** [comment]
Asciidoctor PDF it is then.

@netzwerg I'm hoping that AsciidocFX eventually will support Asciidoctor PDF. That probably will happen once we're past alpha.

**Comment by Mogztter** [comment]
@mojavelinux I've already asked you about this, but do you think we could use Opal to create Prawn.js ?

**Comment by mojavelinux** [comment]
We could certainly try, but I'm having a tough time wrapping my head around it working. It looks like prawn only depends on pdf-core and ttfunk, so hopefully that limits the surface area we have to cover with the transpile.

**Comment by rahmanusta** [comment]
We want to support asciidoctor-pdf in AsciidocFX. I'm working on a new release, maybe we can do it after next release.

**Comment by ldez** [comment]
The binding to asciidoctor-pdf is ready as experimental feature with minimal option. (small steps, always small steps :wink: )

Only need beta testers :smile:

**Comment by netzwerg** [comment]
@ldez Excellent – I gave your implementation a spin on OSX and it works like a charm!

Would it be possible to bundle asciidoctor-pdf? Sorry if this is a stupid question, but for me, the main motivation of having "Save As PDF"-support in Atom would be to alleviate the need for manually installed ruby gems.

**Comment by ldez** [comment]
@netzwerg super!
For now, there is no implementation of asciidoctor-pdf in Javascript.
And bundle an Atom package with Ruby gem is not a good idea.

But if `prawn.js` is created, I can use it!

**Comment by mojavelinux** [comment]
> Would it be possible to bundle asciidoctor-pdf? 

I don't think that would be a good idea*. However, I do think that we can find a way/ways to make installation of the gem more clear/automated.

\* Until we're able to make Asciidoctor.js PDF.

**Comment by ldez** [comment]
The version 2.3.0 contains this new feature :tada:
