### ISSUE TITLE
Attribute :numbering!: is ignored

### ISSUE THREAD

**Issue by neontapir** [asciidoctor/atom-asciidoc-preview#173]
## Description

When using section headers, the numbering attribute should control whether the section header is numbered. The Asciidoctor,js Live Preview Chrome extension does this, so I feel confident my syntax is right, but the Atom previewer does not obey `:numbering!:`.

## Screenshots

![screen shot 2016-06-06 at 11 16 23](https://cloud.githubusercontent.com/assets/96451/15830945/2d27d332-2bd8-11e6-8c60-033fbee36b8b.png)

I would expect the header not to have "1." prefixed.

## Syntax example

```adoc
:numbering!:

= Sample Document

== Sample header
```

**Comment by ldez** [comment]
The Asciidoc Preview package override document attribute for this case:

![capture du 2016-06-06 19-42-24](https://cloud.githubusercontent.com/assets/5674651/15831652/ee7d65a6-2c1e-11e6-99a0-da9bb139f2a5.png)

> Asciidoctor still supports the attribute name `numbered` to number sections for backward compatibility with AsciiDoc Python, but the name `sectnums` is preferred.

http://asciidoctor.org/docs/user-manual/#numbering

**Comment by neontapir** [comment]
Actually, it appears that the section numbering configuration in the screenshot doesn't take precedence over the "Show Numbered Headings" checkbox about five items below that. I found that no matter what I did to the top setting, I always got section numbering.

![screen shot 2016-06-06 at 11 57 33](https://cloud.githubusercontent.com/assets/96451/15832095/e39c575a-2bdd-11e6-840f-667912ab2e6a.png)

**Comment by ldez** [comment]
Have you try with `sectnums` in you document?

Otherwise, if you want to have a full control with the document choose `not-specified` in the settings.

**Comment by neontapir** [comment]
Alas, that's what I'm saying. None of the in-document attributes I'm trying (`:sectnums:` among them) are having any effect. 

I'd like to be able to preview a document with this structure:

````adoc
:sectnums:

= Sample Document

== Sample header

:sectnums!:
== Sample appendix
````

**Comment by neontapir** [comment]
Aha, I figured it out! If you choose the settings by right-clicking the preview, it behaves as you described. I'd been changing the plugin's global settings.

**Comment by ldez** [comment]
right-clicking in the preview and plugin's global settings change options by the same way.

I'm not sure to understand: when you change plugin's global settings you don't have any effects?

**Comment by neontapir** [comment]
Just that checkbox I mentioned before. I guess this is a separate issue in a sense, so I'll reopen this report for tracking.

**Comment by ldez** [comment]
ok I understand!
You are using the package in dev mode?

This option have been deleted.
You can edit your configuration file (Menu > Edit > Config...) and remove replace you current configuration for the package by this line:

```coffee
  "asciidoc-preview": {}
```

**Comment by neontapir** [comment]
I did and it's behaving better, thanks.

**Comment by ldez** [comment]
![anim](https://cloud.githubusercontent.com/assets/5674651/15834289/051511a4-2c2b-11e6-8db9-1ec1cb52799c.gif)

**Comment by neontapir** [comment]
How did you record the animation? I haven't seen that before. Powerful technique.

**Comment by ldez** [comment]
I use [SilentCast](https://github.com/colinkeenan/silentcast).
It's a powerful tool to create animated gif on Linux (It's a GUI for [imagemagik](http://www.imagemagick.org)).

**Comment by neontapir** [comment]
Cool, I'll check it out

**Comment by mojavelinux** [comment]
> This option have been deleted.

I find that when we delete options, sometimes they can linger in the Atom settings. Just keep that mind.

**Comment by ldez** [comment]
@mojavelinux This is why I added an animation that we can re-use. :wink:
