### ISSUE TITLE
Update preview on save does not work: Render on save

### ISSUE THREAD

**Issue by MartinNowack** [asciidoctor/atom-asciidoc-preview#180]
## Description
I've got the option "Render on save" checked, still the preview does not get updated on save.

- Atom version: 1.8.0
- OS: Mac OS X El Capitan
- `asciidoc-preview` version: 2.4.0
- `language-asciidoc` version: 1.5.1

## Syntax example

```adoc
= Foo

== Bar
* Test

```
By the way, the title is not displayed since the last update.

**Comment by ldez** [comment]
@MartinNowack the title in the document preview or in the preview tab ?

**Comment by ldez** [comment]
Can you verify your package settings ?

![capture du 2016-06-15 18-52-35](https://cloud.githubusercontent.com/assets/5674651/16089225/6f0b5e78-332a-11e6-9ab6-a0c27c1317b6.png)

**Comment by MartinNowack** [comment]
Both issues solved.
Fantastic! Thanks a lot.
(Only thing I had to restart Atom after update - but for me it's fine.)
