### ISSUE TITLE
include::xxx.... is rendering as URL

### ISSUE THREAD

**Issue by PaulAndersonMule** [asciidoctor/atom-asciidoc-preview#182]
## Description

*incredibly this bug is gone after an Atom restart (no updates done in between)*

include::xxx.... is rendering as URL

- Atom version: 1.8.0
- OS: OSX 10.11.5 (15F34)
- `asciidoc-preview` version: 2.4.1
- `language-asciidoc` version: 1.5.1

## Screenshots

include::xxx.... is rendering as URL - trust me. It does not do this with asciidoctor commandline

## Syntax example

```adoc
include::someDocument_noHeader.adoc[]
```

**Comment by Mogztter** [comment]
I think you need to configure "Safe mode" to `safe`

![safe-mode](https://cloud.githubusercontent.com/assets/333276/16098055/8079ff58-3351-11e6-9cc4-066706cb9892.png)
http://asciidoctor.org/docs/user-manual/#running-asciidoctor-securely

**Comment by ldez** [comment]
@PaulAndersonMule have you tried to change your settings as the @Mogztter's suggestion?

**Comment by PaulAndersonMule** [comment]
@ldez @Mogztter I had not tried that until now (I specifically need to be 'unsafe' because I have external files.)

However, the preview fails even in safe-mode

```
Error: ENOENT: no such file or directory, open '/var/folders/45/jc7tm14n6jlbww0qz8q_pgmm0000gp/T/asciidoctor116516-11436-ssside/temp.html'
    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:159:20)
    at Object.fs.readFileSync (fs.js:431:33)
    at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:427:29)
    at .....etc./.atom/packages/asciidoctor-prev
```

**Comment by ldez** [comment]
@PaulAndersonMule Can you provide example?

**Comment by PaulAndersonMule** [comment]
I wish I could! - the problem plagued me for 20 minutes until I killed Atom
and restarted it - then problem went away. It's almost like using Windows .
..

On Thu, Jun 16, 2016 at 5:36 PM, Ludovic Fernandez <notifications@github.com
> wrote:

> @PaulAndersonMule <https://github.com/PaulAndersonMule> Can you provide
> example?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/asciidoctor/atom-asciidoc-preview/issues/182#issuecomment-226633784>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AFu-1lkNvOYRyb3_4gzog2PXR2YF7tOIks5qMc_ggaJpZM4I2ze_>
> .
>



-- 
*Paul Anderson PhD*
Principal Architect
mobile: 815-451-7097
MuleSoft <http://www.mulesoft.com/>

**Comment by Mogztter** [comment]
> It's almost like using Windows .

Please stay polite :wink:

**Comment by ldez** [comment]
@PaulAndersonMule can you try with the version 2.5.0?

I have added a new option:

![capture du 2016-06-18 19-28-17](https://cloud.githubusercontent.com/assets/5674651/16172497/284da83e-358b-11e6-972a-7c2be82c6d6c.png)

Configure:
- "Safe mode" to `unsafe`
- "Base directory" to `-`

**Comment by ldez** [comment]
@PaulAndersonMule Is that the problem solved?

**Comment by PaulAndersonMule** [comment]
yes thank you - I could not believe that it really was broken, suspected a corrupted file. I delete Atom entirely (left the ~/.atom directory intact), and reinstalled it, and that highlights problem went away.

**Comment by PaulAndersonMule** [comment]
@ldez yes - I am back into full Atom & adoc-preview functionality now
