### ISSUE TITLE
Inner document links not working within included pages

### ISSUE THREAD

**Issue by mattadamson** [asciidoctor/atom-asciidoc-preview#191]
Team,

Inner document references don't appear to work when they are referenced and opened within a child included page off the root adoc file. 

Consider I have a root file called `root.adoc` which includes

``` adoc
include::logon.adoc[]
include::pagea.adoc[]
```

`pagea.adoc` actually contains a link to a ref declared in `logon.adoc` e.g

```
<<_logonoverview>>
```

If I open `pagea.adoc` it doesn't seem to resolve the reference and simply shows the overview ref id "logonoverview" with no workable link.

This is similar to https://github.com/asciidoctor/atom-asciidoc-preview/issues/189 however thought it better to open a separate issue as quite distinct.

Thanks

**Comment by ldez** [comment]
I'm not sure to understand your problem.

I created some files to reproduce:

- `root.adoc`
```adoc
= Issue 191

include::logon.adoc[]

include::pagea.adoc[]
```

- `logon.adoc`
```adoc
== Logon

[[_logonoverview]]
=== logonoverview

foo

```

- `pagea.adoc`
```adoc
== Page A

<<_logonoverview>>

foo and bar

```

Am I right ?

When you open `pagea.adoc`, the AsciiDoctor parser doesn't see the content of `logon.adoc`, the xref is render like a raw link, this is normal.
The preview can't create link between document if the parser doesn't create them.

- `logon.adoc`
![logon](https://cloud.githubusercontent.com/assets/5674651/16542509/6c5dabb6-40ab-11e6-8e86-84f200855591.png)

- `pagea.adoc`
![page-a](https://cloud.githubusercontent.com/assets/5674651/16542510/6c60f172-40ab-11e6-8b2d-928d8a9919dd.png)

- `root.adoc`
![root](https://cloud.githubusercontent.com/assets/5674651/16542511/6c640ccc-40ab-11e6-9ab0-495275501351.png)

**Comment by mojavelinux** [comment]
> If I open pagea.adoc it doesn't seem to resolve the reference and simply shows the overview ref id "logonoverview" with no workable link.

This observation is correct. Inter-document cross references do not reach into the other file to grab the reference text. They only work that way when included in the same parent document. (In other words, if the sources get merged, then it acts like a regular cross reference. If not, then it links to the other file without automatic reference text).

**Comment by mattadamson** [comment]
thanks both. @mojavelinux however this linkage does work fine when I build my HTML file directly using the asciidoctor maven plug in.  This is why I raised because it works when we build the documentation standalone from our root.adoc file but doesn't work through the atom asciidoc preview feature. If this is not currently supported that's fine just noting a difference.

**Comment by mojavelinux** [comment]
That's not quite what I'm saying. Yes, if it works when you generate the HTML with Asciidoctor, then it should work in the preview.

The key to working through these issues is to provide samples, like @ldez has done.

If you follow the example provided by @ldez, you should see that when you open root.adoc, then label to the reference works correctly.

My guess is that this has to do with an idprefix and idseparator setting issue. If those are different between the two environments, then the IDs will not be matched properly. I would check to make sure the generated IDs are the same or you are using explicit IDs.

**Comment by ldez** [comment]
any news?

**Comment by ldez** [comment]
@mattadamson any news?

**Comment by mattadamson** [comment]
Referencing the example @ldez added this is exactly the case I see in my local project i.e. opening pagea.adoc does not resolve the link correctly. However if you built this using the ascii doctor to html from the root file it would of course generated all links fine.  We can certainly close this as an explanation is provided however perhaps an enhancement later might be for the atom preview plug in to have an "awareness" of the root page e.g. root.adoc here so when opening other pages directly it could build the full tree and be able to resolve these links regardless of which root / child pages define them.
