### ISSUE TITLE
Document can't be exported as PDF

### ISSUE THREAD

**Issue by cmoulliard** [asciidoctor/atom-asciidoc-preview#195]
## Description

The html document generated from asciidoctor can't be exported as pdf. I don't see the option export as pdf

- Atom version: 1.9.8
- OS: MacOs
- `asciidoc-preview` version: 2.5.2
- `language-asciidoc` version: 1.5.1

## Screenshots

![screenshot 2016-08-12 13 23 33](https://cloud.githubusercontent.com/assets/463790/17620909/0ae4324c-6090-11e6-96c2-009c9589bffc.png)

**Comment by Mogztter** [comment]
As a workaround you can save the document as HTML and export the HTML page to PDF from Chrome.

Do you want to be able to convert an AsciiDoc document to PDF using [the native PDF converter](https://github.com/asciidoctor/asciidoctor-pdf) or just an easier/quicker way to export an HTML page to PDF from Atom ?

**Comment by ldez** [comment]
You can activate the package experimental feature:
- Install [asciidoctor-pdf](https://github.com/asciidoctor/asciidoctor-pdf)
- Settings:
![capture du 2016-08-12 19-28-16](https://cloud.githubusercontent.com/assets/5674651/17631115/ffe763ea-60c2-11e6-8c9e-7c52aec466d5.png)
- Right-click on the file in the file browser (left panel)

**Comment by cmoulliard** [comment]
I can export the document. I must figure out now a bash issue with Atom

![screenshot 2016-08-13 10 02 47](https://cloud.githubusercontent.com/assets/463790/17642201/2b935c0e-613d-11e6-8c67-e6198e267918.png)

**Comment by ldez** [comment]
ENOENT: Error NO ENTry

To defined the shell to use, we use environment variable `SHELL` or if this variable doesn't exist we explicitly call `bash`.

Can you try to manually call `/bin/bash -l -i` ?

**Comment by cmoulliard** [comment]
I can execute the command `/bin/bash -l -i ` within a terminal of MacOS

**Comment by ldez** [comment]
I reproduce on Linux, I'm trying to solve the problem.

**Comment by ldez** [comment]
It's a regression caused by core changes in Atom 1.9.
