### ISSUE TITLE
HTML entity as variable replacement in headers

### ISSUE THREAD

**Issue by AFulgens** [asciidoctor/atom-asciidoc-preview#198]
## Description

HTML entities as variable replacement in headers do not work in the preview.

*Note:* it may be a PEBKAC, does it even work in AsciiDoc? (i.e., I did not test it)

- Atom version: 1.8.0
- OS: Win10
- `asciidoc-preview` version: 2.5.3
- `language-asciidoc` version: 1.5.1

## Screenshots

![image](https://cloud.githubusercontent.com/assets/8810011/17802366/35015d6a-65f0-11e6-9290-a0e0544846fb.png)

## Syntax example

```adoc
:todo: &#9744;
:done: &#9745;

# header {todo} &#9744;

{done} step done

{todo} step todo
```

**Comment by ldez** [comment]
Hello,

I don't have the full explanation of this behavior but it's the AsciiDoctor behavior.

Related to http://asciidoctor.org/docs/user-manual/#subs.

**Comment by mojavelinux** [comment]
@ldez That is exactly the correct explanation. This is one of those things I've never understood about AsciiDoc and would like to see changed. I say as much in the following issue, in which I also explain the workaround: https://github.com/asciidoctor/asciidoctor/issues/1173

This is not an issue with this Atom plugin and should therefore be closed.
