### ISSUE TITLE
Preview window does not fill the frame

### ISSUE THREAD

**Issue by getreu** [asciidoctor/atom-asciidoc-preview#199]
## Description

Preview window does not fill the frame (see screen shot).

- Atom version: 1.11.0-beta 3
- OS: Linux
- `asciidoc-preview` version: 0.3.0
- `language-asciidoc` version: 1.5.1

## Screenshots
![screenshot - 060916 - 21 34 39](https://cloud.githubusercontent.com/assets/579082/18286204/6b50a7f2-747a-11e6-9229-5db8bd4da5d6.png)

## Syntax example

```adoc
== Invocation

A2pdf::
+
----
  adoc2docbook2pdf -r asciidoctor-bibtex -r asciidoctor-diagram "%"
----

A2pdf2::
----
  asciidoctor-pdf -r asciidoctor-bibtex -r asciidoctor-diagram "%"; mupdf "%<.pdf"&
----

A2html::
----
  asciidoctor     -r asciidoctor-bibtex -r asciidoctor-diagram -b xhtml5 "%"; iceweasel "%<.html"&
----

A2slides::
----
  asciidoctor -T ./asciidoctor-reveal.js/templates/slim -r asciidoctor-bibtex -r asciidoctor-diagram  "%"; iceweasel "%<.html"&
----

```

**Comment by ldez** [comment]
Can you update `asciidoc-preview` to the latest version (2.6.0) ?

**Comment by getreu** [comment]
Yes, sorry! I just saw that I installed an obsolete version. 2.6.0 works fine, except I could not get asciidoctor-bibtex working. But this is another issue.
