### ISSUE TITLE
Live previewing make editor stuck 

### ISSUE THREAD

**Issue by smartwjw** [asciidoctor/atom-asciidoc-preview#200]
## Description

When I opened live previewing and typed in editor, the editor got stuck for a few seconds, however,
when live previewing is closed, the editor runs smoothly. 
- Atom version: 

```
    Atom    : 1.10.2
    Electron: 0.37.8
    Chrome  : 49.0.2623.75
    Node    : 5.10.0
```
- OS:  Mac OSX 10.11.6
- `asciidoc-preview` version: 2.6.0
- `language-asciidoc` version: 1.5.1

Activity Monitor shows `fontd` process at high cpu usage state:
![2aa76a25-1935-4d0d-b623-ab42b3cb2f04](https://cloud.githubusercontent.com/assets/1625837/18343782/567c98ae-75e7-11e6-9bb1-555b2a08079a.png)

**Comment by ldez** [comment]
Hello,

Have you trying the same thing with the Markdown preview ?

**Comment by smartwjw** [comment]
Yes, Markdown preview is very smooth. But, recently  atom upgrade to 1.11.2, it seems that Asciidockor preview back to normal.

**Comment by ldez** [comment]
We can close this issue ?

**Comment by Foadsf** [comment]
Same issue here. I'm developing a small library prototype which you can see [here](http://bit.ly/2HwqPJs). However Atom is stuck rendering it:

![2019-03-15_12-53-18](https://user-images.githubusercontent.com/12762442/54429755-ae94f000-4721-11e9-9b49-71f637865210.gif)

**Comment by Mogztter** [comment]
@Foadsf Could you please open the devtools and look for errors in the console ?

**Comment by Foadsf** [comment]
@Mogztter Could you pleas elaborate with the instructions? My code is [here ](https://gist.github.com/Foadsf/44fe9b5e2bcb02b22392adf6d8f7a871) BTW if you want to try yourself.

**Comment by Mogztter** [comment]
I can't find any documentation on Atom but `Ctrl+Alt+I` should open the developer tools with console.
On macOS, I think it's `Cmd+Opt+I`. 

https://flight-manual.atom.io/hacking-atom/sections/debugging/#diagnose-runtime-performance

**Comment by Foadsf** [comment]
@Mogztter Nothing shows up with that keyboard shortcut. from the menu bar maybe?

**Comment by Foadsf** [comment]
@Mogztter  aha ctril+shift + I on windows [link](https://discuss.atom.io/t/how-to-make-developer-tools-appear/16232/2)

**Comment by Foadsf** [comment]
Here is the error:

```
Uncaught (in promise) TypeError: grammar.tokenizeLines is not a function
    at highlightSync (highlights.coffee:44)
    at tokenizeCodeBlocks (renderer.coffee:145)
    at renderer.coffee:23
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188)
```

**Comment by Mogztter** [comment]
I think it's related to https://github.com/asciidoctor/atom-asciidoc-preview/issues/279#issuecomment-434883201
And quoting myself, we definitely need to add this issue in the README: https://github.com/asciidoctor/atom-asciidoc-preview/issues/279#issuecomment-447660219

If I have some time tonight I will submit a pull request :wink: 

@Foadsf Could you please confirm that disabling tree-sitter parsers, solve your issue ?

**Comment by Foadsf** [comment]
@Mogztter  I have no idea how I should disable the "tree-sitter parsers" but I suppose it is something discuses on those links. I will do this tonight too. Anyways my code is [here ](https://gist.github.com/Foadsf/44fe9b5e2bcb02b22392adf6d8f7a871) for testing. I appreciate your kind support.

**Comment by Mogztter** [comment]
>  have no idea how I should disable the "tree-sitter parsers" but I suppose it is something discuses on those links. 

Not really, here's a detailed guide:

1. Open the "Settings View"

![settings](https://user-images.githubusercontent.com/333276/54434225-0df8fd00-472e-11e9-9d4a-af9be905e450.png)


2. In "Core" tab (ie. the default tab), scroll to the bottom:

![core-settings](https://user-images.githubusercontent.com/333276/54434250-1e10dc80-472e-11e9-99a4-524637c5846c.png)

3. Uncheck "Use Tree Sitter Parsers"

>  I appreciate your kind support.

You're welcome, I'm glad to help :hugs:

**Comment by Foadsf** [comment]
@Mogztter It does render now, however the collapsible section oesn't work and the code block inside it doesn't have syntax highlighting!

**Comment by Foadsf** [comment]
@Mogztter I checked on a different computer. Now the syntax highlighting works upon disabling `tree-sitter parsers` , however the collapsible part doesn't. The collapsible part works on vscode FYI.

**Comment by mojavelinux** [comment]
> however the collapsible part doesn't. The collapsible part works on vscode FYI.

I don't think collapsible blocks is a feature of this plugin.

**Comment by Foadsf** [comment]
isn't the rendering engine of this plugin and vscode one the same?

**Comment by mojavelinux** [comment]
Yes and no. The preview window uses Asciidoctor.js. But the editor window uses a very different technology stack.

**Comment by Foadsf** [comment]
the editors window is great in both atom and vscode. No issues there. foldable / collapsible part I have implementation using HTML tags doesn't work in the preview section of Atom.

**Comment by mojavelinux** [comment]
I'm afraid I don't know what you are talking about. Is this a custom extension you've added to the converted page? Could you show a screenshot or code?

**Comment by Foadsf** [comment]
[here](https://gist.github.com/Foadsf/44fe9b5e2bcb02b22392adf6d8f7a871) my code. please note the part with

```
////
<details>
  <summary>Click to see the source code</summary>
////


collapsible part

////
</details>
////
```

**Comment by mojavelinux** [comment]
This could be a limitation of the HTML viewer in Atom. Have you tried the same thing in the Markdown preview?

Btw, I strongly recommend against putting HTML directly in your AsciiDoc file. It would be much better if you created a custom block extension (or custom converter). It looks like you are attempting to implement https://github.com/asciidoctor/asciidoctor/issues/1699.

**Comment by Foadsf** [comment]
**Markdown :**


code

~~~markdown
/*

This is the markdown **text** 

used for documentation

<details>
  <summary>Click to see the source code</summary>

``` scilab 
*/
This is the
  actual code
  which will 
be executed
/*
```

</details>

<!--- */ // -->
~~~


**GitHub:**

/*

This is the markdown **text** 

used for documentation

<details>
  <summary>Click to see the source code</summary>

``` scilab 
*/
This is the
  actual code
  which will 
be executed
/*
```

</details>



**Atom:**

![5tgyM1BBLu](https://user-images.githubusercontent.com/12762442/54480060-6dd1cf80-4824-11e9-9fd6-b037ef69c9d8.gif)


**VSCode:**

![WIeqpXouGh](https://user-images.githubusercontent.com/12762442/54480067-8346f980-4824-11e9-91c8-d4bb2317b3b9.gif)

**Comment by Foadsf** [comment]
# AsciiDoc:

## Code:

~~~asciidoc
////
/*
////
This is the markdown **text** 

used for documentation

+++ <details><summary> +++
Click to see the source code
+++ </summary><div> +++

[source,scilab]
....
*/
This is the
  actual code
  which will 
be executed
/*
....

+++ </div></details> +++
////
*/
////
~~~


## Atom:

![PGMRHtNYUx](https://user-images.githubusercontent.com/12762442/54480196-d0779b00-4825-11e9-9026-8c22f73b0597.gif)


## VSCode:

![Mplx4P5ivf](https://user-images.githubusercontent.com/12762442/54480210-ff8e0c80-4825-11e9-9047-1548d7b2e98d.gif)

**Comment by Foadsf** [comment]
A comparison between different options so far:

|         | Color layout | Syntax highlighting | Collapsible | Include | Other file extensions |                                       Relevant discussion                                      |
|:-------:|:------------:|:-------------------:|:-----------:|:-------:|:---------------------:|:----------------------------------------------------------------------------------------------:|
|   Atom  |       ✔️      |          ✔️          |      ❌      |    ✔️    |           ❌           | [here](https://github.com/asciidoctor/atom-asciidoc-preview/issues/200#issuecomment-473575038) |
|  VSCode |       ❌      |          ❌          |      ✔️      |    ✔️    |           ❌           |              [here](https://github.com/asciidoctor/asciidoctor-vscode/issues/171)              |
| Browser |       ~      |          ❌          |      ~✔️     |    ❌    |           ✔️           |         [here](https://github.com/asciidoctor/asciidoctor-browser-extension/issues/276)        |

**Comment by Foadsf** [comment]
Dear @mojavelinux and @Mogztter should I open a new issue for the Atom live preview not rendering the `summary` element properly? It doesn't seem to be relevant here.

**Comment by mojavelinux** [comment]
The stylesheet provided by Asciidoctor Ruby will carry over to the Atom live preview once Asciidoctor.js is upgraded (the stylesheet is part of the upgrade).

**Comment by Foadsf** [comment]
@Mogztter and @mojavelinux the Atom plugin just got updated and now the live preview syntax highlighting doesn't work anymore. Should I open a new issue for this or it is relevant to any of other issues we already have and I should just wait for the new PRs?

**Comment by ldez** [comment]
@Foadsf could you open a new issue?
