### ISSUE TITLE
After updating the preview window display the bottom of it

### ISSUE THREAD

**Issue by cuinixam** [asciidoctor/atom-asciidoc-preview#206]
## Description

When I write new _adoc_ files, in almost all the cases, I find myself editing at the bottom of the file.
While the file is getting bigger I find myself scrolling down the preview to see the result.

Until a _synch_ functionality is implemented it would be great if after updating the preview I can see directly the bottom of it and not the top.

- Atom version: 1.12.6
- OS: Windows 7
- `asciidoc-preview` version: 2.7.1
- `language-asciidoc` version: 1.6.2

**Comment by mojavelinux** [comment]
I agree this behavior is annoying. However, I wouldn't recommend spending any time on this workaround. Instead, that time should be spent working on sync. I say that because sync is already implemented in tools that use exactly the same technology...so we already know it's possible and there's a reference. I totally agree we need a better experience...I just think anyone spending time on it should just do it the right way first.

**Comment by cuinixam** [comment]
Sure, it is only worth if the effort is very low and I thought this could be fixed with something like "scroll to bottom" after updating the preview :D

**Comment by mojavelinux** [comment]
If it does turn out to be complicated, I agree this could be a reasonable
stopgap to buy more time.

**Comment by ldez** [comment]
Related to #82

**Comment by ldez** [comment]
@mojavelinux 
> sync is already implemented in tools that use exactly the same technology
not really: the way of Asciidoctor render and the way to render in Atom, are really different from other Atom package.

**Comment by mojavelinux** [comment]
> the way of Asciidoctor render and the way to render in Atom, are really different from other Atom package.

I agree, the Ruby version of Asciidoctor render is different. But both AsciidocFX and Brackets use sync using Asciidoctor.js, so we should be able to study that code. (I'm aware that the IntelliJ plugin code won't help us much because that is a different way).

**Comment by mojavelinux** [comment]
...but if I'm over generalizing, I apologize.

**Comment by ldez** [comment]
Fix by #216
