### ISSUE TITLE
matching underscores inside quoted code block are treated as italic markers

### ISSUE THREAD

**Issue by handcraftsman** [asciidoctor/atom-asciidoc-preview#207]
## Description

    `__str__` 

is rendered as an italic code block like _`str`_ but should be rendered as a code block containing underscores like `__str__`.

- Atom version: 1.12.7
- OS: Windows 19
- `asciidoc-preview` version: 2.7.1 (was also in 2.6.0, 2.7.0)

**Comment by ldez** [comment]
The render is correct: monoscape + italic.

We have the same behavior as http://gist.asciidoctor.org and we respect the specification.

**Comment by ldez** [comment]
to doing what you want you must use passthrough macro.
```adoc

`pass:[__str__]`

`+++__str__+++`

`$$__str__$$`

```

**Comment by mojavelinux** [comment]
Actually, it's even simpler:

```
`+__str__+`
```

The backticks make it monospace. The pluses make it literal (as entered), but would still escape special characters. We separated these two functions in Asciidoctor 1.5.0. See http://asciidoctor.org/docs/migration/#migration-cheatsheet.

**Comment by handcraftsman** [comment]
Note this differs from the behavior of asciidoctor-pdf which currently renders it as monospace with visible underscores.  I assumed that was the correct behavior and noticed the difference in rendering when editing in Atom.

![str](https://cloud.githubusercontent.com/assets/234664/21158229/fe3749b8-c141-11e6-9d2b-d8293681e7ae.png)

**Comment by mojavelinux** [comment]
It shouldn't be different. What version of Asciidoctor PDF are you using?

If I type:

```
`__str__`
```

I get *`str`* in Asciidoctor PDF.

If I type:

```
`+__str__+`
```

I get `__str__` in Asciidoctor PDF.

**Comment by handcraftsman** [comment]
In Asciidoctor PDF 1.5.0.alpha.13 using Asciidoctor 1.5.5 it is rendering with visible underscores like `__str__`, which is what I wanted so I thought that was normal.  No problem.  I'll change my markup.  Sorry for the confusion.

**Comment by mojavelinux** [comment]
Just to confirm, you are saying that `+__str__+` gives you the result you expect? If so, :+1:

**Comment by mojavelinux** [comment]
I think the issue is compat-mode. See http://asciidoctor.org/docs/migration/#compat-mode. This affects this behavior. Generally, you should not be using compat-mode unless you are converting an old document.
