### ISSUE TITLE
Specifying theme file for PDF export

### ISSUE THREAD

**Issue by borisovg** [asciidoctor/atom-asciidoc-preview#208]
## Description

At the moment there seems to be no way to specify theme file for the PDF export. I would like to specify one to override the silly table stripes.

## Version info

- Atom version: 1.12.7
- OS: Debian GNU/Linux (Sid)
- `asciidoc-preview` version: 2.7.1
- `language-asciidoc` version: 1.6.2

**Comment by ldez** [comment]
Not very quick but in the next release I added simple configuration option for the PDF export.
