### ISSUE TITLE
"Export as PDF" fails for filenames with whitespaces

### ISSUE THREAD

**Issue by bentolor** [asciidoctor/atom-asciidoc-preview#212]
## Description

The "AsciiDoc: Export as PDF" option fails for files with whitespaces in them and complains for a missing file with an incomplete filename.

1. Enable / Setup PDF File generation for atom-asciidoc-preview
2. Create a file /tmp/Foo Bar.adoc
3. Select file in file Tree & choose _"AsciiDoc: Export as PDF"_

- Atom version: 1.13.1
- OS: Mint 18.1 
- `asciidoc-preview` version: 2.7.1
- `language-asciidoc` version: 1.7.0

## Screenshots

![failure-whitespace-files](https://cloud.githubusercontent.com/assets/588260/22777351/356f3960-eeb3-11e6-92e3-7fb1ad2691f1.png)

**Comment by ldez** [comment]
Thanks for reporting.

Fixed in the next release.
