### ISSUE TITLE
Asciidoc Preview Don't popup

### ISSUE THREAD

**Issue by DestructiveBurn** [asciidoctor/atom-asciidoc-preview#215]
## Description

Your description.
Your Preview plugin will not popup and become active.
- Atom version: 1.14.4 x64
- OS: Windows 7 64-bit SP1
- `asciidoc-preview` version:
- `language-asciidoc` version: 2.7.2?

## Screenshots

Your screenshot.
No point.  Wont popup to show that
## Syntax example

```adoc
Your syntax example.
```

**Comment by ldez** [comment]
There not popup in the Preview package, I don't understand your problem.
Can you add more detailed explanation ?

**Comment by DestructiveBurn** [comment]
O crap sorry.  I was trying to use it for .html pages.  I missed your:
(currently enabled for .adoc, .asciidoc, .ad, .asc, .adoc.txt, .txt files.)
Sorry man.  Too bad it don't work for HTML pages.   Do you know one that will?
