### ISSUE TITLE
Offset scroll preview window when syncing with source

### ISSUE THREAD

**Issue by lucascosti** [asciidoctor/atom-asciidoc-preview#222]
Enhancement suggestion for the new scroll syncing feature:

With the current implementation, when the preview scroll is synced with the cursor position from the source pane, the preview shows the synced line as the as the very top of the preview.

Generally, when I am editing source I have it scrolled to the middle of the pane, rather than the top, so I can see the context above and below what I am writing (and it's also more comfortable to look at the middle of the screen, rather than the top).

Now that the preview sync is implemented, I would love a configurable option to offset the synced preview from the top of the pane (in places where the document makes that possible).

I have no idea if it is possible, but ideally the synced line should be in the same position in the preview pane as the cursor is in the editor pane. Otherwise, maybe a configurable percentage offset would do?

**Comment by mojavelinux** [comment]
Yep, this is certainly possible. We can either add a fixed amount, or we can try to calculate the middle dynamically. The block itself won't be centered because that depends on the height of the block. But the first line can be centered within the viewport.

What we'll need to decide on is the description of the option. Please propose a line for the configuration screen.

**Comment by lucascosti** [comment]
> What we'll need to decide on is the description of the option. Please propose a line for the configuration screen.

okay, for the 'matched position' implementation, something like:

_Align the synced preview pane to the same vertical position as the cursor in the editor pane._

Or, for the centered implementation:

_Scroll the synced location to the center of the preview pane._

**Comment by mojavelinux** [comment]
I kind of like the matched position. If we choose to allow both options, then these would be entries in a select form field.

**Comment by mojavelinux** [comment]
(oops, got twitchy with the Comment button)
