### ISSUE TITLE
Cannot load /usr/lib64/atom/node_modules/highlights

### ISSUE THREAD

**Issue by pmkovar** [asciidoctor/atom-asciidoc-preview#223]
## Description

asciidoc-preview fails to start with a cannot load the /usr/lib64/atom/node_modules/highlights module error.

- Atom version: 1.14.1
- OS: Fedora
- `asciidoc-preview` version: 2.9.0
- `language-asciidoc` version: 1.8.0

Creating the following symlink fixes the issue:

    ln -s /usr/lib64/atom/node_modules/highlight.js/ /usr/lib64/atom/node_modules/highlights

Apparently, asciidoc-preview should point to ``highlight.js`` instead of ``highlights``.

**Comment by ldez** [comment]
you have a problem with your Atom installation.

See #187, #150, #91, #65

**Comment by ldez** [comment]
Do you have the `markdown-preview` package ?

**Comment by mojavelinux** [comment]
As @ldez pointed out, highlights and highlight.js are not the same package (and very different things). highlights is the core syntax highlighter in Atom. See https://www.npmjs.com/package/highlights.

**Comment by ldez** [comment]
Closed see #226
