### ISSUE TITLE
Uncaught Error: Cannot find module '/usr/lib64/atom/node_modules/highlights'

### ISSUE THREAD

**Issue by garrett** [asciidoctor/atom-asciidoc-preview#226]
[Enter steps to reproduce:]

1. Install asciidoc-preview
2. Attempt to preview an asciidoc file

This happens consistently, even when nuking ~/.atom/ and only installing asciidoc add-ons.

I notice that there's no package in `/usr/lib64/atom/node_modules/` called `highlights`, but there is one called `/usr/lib64/atom/node_modules/highlight.js/` — perhaps the `asciidoc-preview` is including the wrong package?

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Fedora release
**Thrown From**: [asciidoc-preview](https://github.com/asciidoctor/atom-asciidoc-preview) package 2.9.1

### Stack Trace

Uncaught Error: Cannot find module '/usr/lib64/atom/node_modules/highlights'

```
At module.js:457

Error: Cannot find module '/usr/lib64/atom/node_modules/highlights'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (/usr/lib64/electron/1.3.13/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/usr/lib64/atom/src/module-cache.js:383:52)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (/usr/lib64/atom/src/native-compile-cache.js:50:27)
    at /packages/asciidoc-preview/lib/renderer.coffee:7:14)
    at /packages/asciidoc-preview/lib/renderer.coffee:1:1)
    at Module._compile (/usr/lib64/atom/src/native-compile-cache.js:109:30)
    at Object.value [as .coffee] (/usr/lib64/atom/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/usr/lib64/atom/src/native-compile-cache.js:50:27)
    at /packages/asciidoc-preview/lib/asciidoc-preview-view.coffee:8:12)
    at /packages/asciidoc-preview/lib/asciidoc-preview-view.coffee:1:1)
    at Module._compile (/usr/lib64/atom/src/native-compile-cache.js:109:30)
    at Object.value [as .coffee] (/usr/lib64/atom/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/usr/lib64/atom/src/native-compile-cache.js:50:27)
    at Object.createAsciiDocPreviewView (/packages/asciidoc-preview/lib/main.coffee:91:30)
    at /packages/asciidoc-preview/lib/main.coffee:85:10
    at Workspace.module.exports.Workspace.openURIInPane (/usr/lib64/atom/src/workspace.js:501:22)
    at Workspace.module.exports.Workspace.open (/usr/lib64/atom/src/workspace.js:436:19)
    at Object.addPreviewForEditor (/packages/asciidoc-preview/lib/main.coffee:126:20)
    at Object.previewFile (/packages/asciidoc-preview/lib/main.coffee:135:8)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/lib64/atom/src/command-registry.js:259:29)
    at CommandRegistry.handleCommandEvent (/usr/lib64/atom/src/command-registry.js:3:59)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/usr/lib64/atom/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (/usr/lib64/atom/src/atom-environment.js:1168:28)
    at EventEmitter.outerCallback (/usr/lib64/atom/src/application-delegate.js:325:25)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -1:13 core:confirm (input.hidden-input)
  2x -0:12.5.0 asciidoc-preview:preview-file (span.name.icon.icon-file-text)
```

### Non-Core Packages

```
asciidoc-assistant 0.2.2 
asciidoc-image-helper 1.0.0 
asciidoc-preview 2.9.1 
autocomplete-asciidoc 0.1.2 
language-asciidoc 1.9.0 
```

**Comment by garrett** [comment]
A workaround, at least on Linux:

```
cd /usr/lib64/atom/node_modules
sudo ln -s highlight.js highlights
```

(Of course, this isn't a real fix.)

**Comment by ldez** [comment]
you have a problem with your Atom installation.

See #223 #187, #150, #91, #65

**Comment by ldez** [comment]
Do you have the `markdown-preview` package ?

**Comment by ldez** [comment]
[highlights](https://www.npmjs.com/package/highlights) and [highlight.js](https://www.npmjs.com/package/highlight.js) are not the same package.

**Comment by mojavelinux** [comment]
highlights is the core syntax highlighter in Atom. I'm a little confused myself where it's supposed to end up. I have difficulty finding a reference to highlights in my ~/.atom directory. But surprisingly everything works for me.

**Comment by ldez** [comment]
I think the problem is related to https://github.com/asciidoctor/atom-asciidoc-preview/blob/master/lib/renderer.coffee#L7

We use "relative" path to highlights from `markdown-preview`, if you don't have `markdown-preview` package, this may cause an error.

**Comment by mojavelinux** [comment]
That makes sense. I think we just need to add a dependency on highlights. Is that what you are thinking?

**Comment by ldez** [comment]
It's not possible:

https://github.com/asciidoctor/atom-asciidoc-preview/blob/master/lib/renderer.coffee#L6
> # No direct dependence with Highlight because it requires a compilation. See #63 and #150 and atom/highlights#36.

**Comment by ldez** [comment]
I can create a fallback on 'highlights.js' but I think it's a source of bugs and unnecessary complexity.

**Comment by Mogztter** [comment]
I thought Highlights was available as a core module/package in Atom 😐 
Highlighting will not work if `markdown-preview` is not installed ?

**Comment by mojavelinux** [comment]
> I can create a fallback on 'highlights.js' but I think it's a source of bugs and unnecessary complexity.

I agree with that wholeheartedly.

**Comment by mojavelinux** [comment]
> I thought Highlights was available as a core module/package in Atom :neutral_face:
Highlighting will not work if markdown-preview is not installed ?

That's what we need to get clarification on.

One workaround is to simply declare a dependency on markdown-preview (or some other package that pulls it in). It's a little strange, but if it it avoids having to do a compilation, it might be what we have to do.

**Comment by ldez** [comment]
`markdown-preview` is an Atom core package. It's always present except if user disable or uninstall this package.

**Comment by ldez** [comment]
The compilation problem append only on Windows...

**Comment by mojavelinux** [comment]
I understand. Thanks for clarifying that.

**Comment by stesachse** [comment]
`find /usr/lib64/atom/node_modules/ ~/.atom/packages/ -type d -name 'highlights'`

> /usr/lib64/atom/node_modules/styleguide/node_modules/highlights
> /usr/lib64/atom/node_modules/markdown-preview/node_modules/highlights
> /home/white/.atom/packages/rst-preview/node_modules/highlights

there is no package `highlights` in `/usr/lib64/atom/node_modules` but `asciidoc-preview` is [hardcoded](https://github.com/asciidoctor/atom-asciidoc-preview/blob/master/lib/renderer.coffee#L6-L7) to load it from there. however, there is a package `highlights` below the package `markdown-preview`.

this patch change the hard coded path to the correct location

```diff
--- lib/renderer.coffee-fix-require-highlights	2017-04-01 05:58:40.855273143 +0200
+++ lib/renderer.coffee	2017-04-01 06:28:20.980865718 +0200
@@ -4,7 +4,7 @@
 fs = require 'fs-plus'
 cheerio = require 'cheerio'
 # No direct dependence with Highlight because it requires a compilation. See #63 and #150 and atom/highlights#36.
-Highlights = require path.join atom.packages.resolvePackagePath('markdown-preview'), '..', 'highlights'
+Highlights = require path.join atom.packages.resolvePackagePath('markdown-preview'), 'node_modules', 'highlights'
 {scopeForFenceName} = require './highlights-helper'
 
 {makeAttributes, makeOptions} = require './configuration-builder'
```

this works even if the package `markdown-preview` is disabled.

```bash
cson2json ~/.atom/config.cson | jq '.["*"].core.disabledPackages | contains(["markdown-preview"])'
```

> true

`atom --version`

> Atom    : 1.15.0
> Electron: 1.3.13
> Chrome  : 52.0.2743.82
> Node    : 6.5.0

`lsb_release -s -d`

> "Fedora release 25 (Twenty Five)"

**Comment by mojavelinux** [comment]
Now I get it. This makes sense to me. Can you send a PR?

**Comment by ldez** [comment]
the `disabled` state of `markdown-preview` it's not a problem, because Atom download dependencies when a package is disabled.

**Comment by ldez** [comment]
the fix doesn't work for me:

```
Error: Cannot find module '/usr/share/atom/resources/app.asar/node_modules/markdown-preview/node_modules/highlights'
```

**Comment by ldez** [comment]
FYI Atom store plugins dependencies in a tar like file named `app.asar`.

**Comment by ldez** [comment]
I think it's a Fedora specific problem.

**Comment by mojavelinux** [comment]
@garrett What package are you using to install Atom? When I install Atom using the RPM from the Atom project, nothing goes in /usr/lib64. But I'm installing on Fedora 21. Everything goes under /usr/share/atom.

**Comment by mojavelinux** [comment]
Aha! Now we get to the bottom of it. There is another package of atom floating around in a copr.

https://copr.fedorainfracloud.org/coprs/mosquito/atom/packages/

In that package, things are installed in different places. Specifically, everything is under /usr/lib64/atom and all the node modules are expanded (not using the virtual file system). So yes, this is a workaround for Fedora, but specifically for the mosquito/atom copr package.

**Comment by mojavelinux** [comment]
It would have been helpful if the original bug report mentioned that Atom was not installed using the official package. That's something we should capture in the future. Not just your Atom version, but how you installed it.

**Comment by stesachse** [comment]
@mojavelinux imo [mosquito/atom](https://copr.fedorainfracloud.org/coprs/mosquito/atom/) is the only repos with frequent updates

**Comment by mojavelinux** [comment]
I understand that, and I certainly understand wanting to use a native Fedora package instead of the bundle that the Atom team ships (since I'm well aware of Fedora packaging rules). However, the differences in how the packages are arranged does force us to make accommodations. In this case, I think it's a good one since depending on another plugin seems fragile. Ludovic seems to have arrived at an elegant solution.

**Comment by garrett** [comment]
Oh, I installed Atom with `dnf install atom`; I don't have the copr enabled... this is a fresh F26 pre-alpha on a new laptop. 

However, I have [unitedrpms](https://unitedrpms.github.io/) enabled (as I needed it for kdenlive video editing) — and `rpm -qi atom` shows that it's the same as the copr build.

I was shocked that Atom didn't work with AsciiDoc on a clean install and made the assumption that asciidoc-preview was broken… Sorry about that. Also, sorry for the assumption this was a standard Atom package from Fedora. (Sadly, it seems that Fedora still doesn't have Atom packaged officially.)

Thanks, @ldez, for the fix!

**Comment by mojavelinux** [comment]
It actually turns out this was good anyway. @ldez discovered a better approach to using the highlighting system in Atom which gets us away from the highlights wrapper altogether. Win win!
