### ISSUE TITLE
Highlighted source blocks should respect syntax theme

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/atom-asciidoc-preview#231]
## Description

The highlighted source blocks in the preview window should respect the syntax theme like the markdown-preview package. This is matter of setting the right class on the `<pre>` element and using the syntax variables correctly in the stylesheet. We should follow what the markdown-preview does and use a slightly contrasted color from the theme.

- Atom version: 1.15.0 (installed from the official RPM package)
- OS: Fedora 21
- asciidoc-preview: 2.9.1

## Screenshots

You can see that even though I've selected the One Dark theme, the source block has a light gray background.

![syntax-theme-source-block](https://cloud.githubusercontent.com/assets/79351/24585578/a553efb2-174b-11e7-9208-bebc733346e5.png)

## Syntax example

```adoc
[source,ruby]
----
require 'asciidoctor/extensions'

Asciidoctor::Extensions.register do
  treeprocessor do
    process do |doc|
      (doc.find_by context: :dlist).each do |dlist|
        dlist.style = 'horizontal'
      end
      nil
    end
  end
end
----
```

**Comment by ldez** [comment]
`markdown-preview` use embedded Atom editor.
