### ISSUE TITLE
Add Export as PDF option to preview pane

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/atom-asciidoc-preview#237]
## Description

On a number of occasions, I have been confused about where to find Export as PDF function. While I do agree it makes sense to add it to the context menu of the file tree, this is not consistent with the location of the Save as HTML... option.

## Proposed Solution

I think we should either add Export as PDF to the context menu of the preview pane (like Save as HTML...), add Save as HTML... to the context menu of the file tree, or both. What's confusing is that they are in different places.

## Environment

- Atom version: 1.15.0 (installed via the official rpm)
- OS: Linux
- asciidoc-preview version: 2.10.0

**Comment by ldez** [comment]
"Export" and "Save as" don't do the same things, the words are important in this case.

I have already try do this, but it's more complex than add an entry into a menu.

**Comment by mojavelinux** [comment]
> "Export" and "Save as" don't do the same things, the words are important in this case.

Agreed. I'm not questioning the wording.

**Comment by ldez** [comment]
Sorry I misspoke, I mean that the action 'save as' used directly view while I built export PDF to be easily reused.

**Comment by mojavelinux** [comment]
Gotcha.

**Comment by ldez** [comment]
Closed by  #238
