### ISSUE TITLE
PDF Export doesn't work

### ISSUE THREAD

**Issue by Stahlschmidt** [asciidoctor/atom-asciidoc-preview#247]
## Description

When I use the right click and Export As PDF it takes some seconds and then I see 
"Export as PDF completed with errors".
`C:\_Temp\Dokumentationen\Filename.pdf`
When I use the command `asciidoctor-pdf -a pdf-stylesdir=theme -a pdf-style=company Filename.adoc`
In a CMD window it works great.

But there is no PDF created at all and I see no error log or why it doesn't work.

- Atom version: 1.18.0 x64
- OS: Windows 7
- `asciidoc-preview` version: 2.10.2
- `language-asciidoc` version:

## Screenshots

Your screenshot.
![image](https://user-images.githubusercontent.com/30231777/28264496-8b5cc248-6aeb-11e7-98ca-f5bde75eff76.png)

## Syntax example

```adoc
Your syntax example.
```

**Comment by ldez** [comment]
@Stahlschmidt please remove ` -a pdf-stylesdir` and `-a pdf-style=` from the fields.

**Comment by Stahlschmidt** [comment]
Unfortunately that doesn't work as well :-(

Maybe that config helps to see what is wrong?
Inside the folder where my *.adoc is stored there is a sub-folder "theme" and config file name is "company-theme.yml"

----
"*":
  "asciidoc-image-helper":
    customFilenames: true
    imageFolder:
      append: false
  "asciidoc-preview":
    exportAsPdf:
      enabled: true
      pdfStyle: "company"
      pdfStylesDir: "theme"
  core:
    telemetryConsent: "limited"
  editor:
    softWrap: true
  "exception-reporting":
    userId: "a69026ae-f629-4916-9aac-67976486d884"
  welcome:
    showOnStartup: false
----

**Comment by ldez** [comment]
Could you try to define a absolute path to your style directory?

**Comment by Stahlschmidt** [comment]
In Windows or Linux format? with or without "" ?
Path is: C:\_Temp\Dokumentationen

**Comment by Stahlschmidt** [comment]
Okay, the Full Path to theme dir is working in Windows Format without ""
C:\_Temp\Dokumentationen\theme

I've tried the full path with '-a pdf-stylesdir=' but that has not worked as well.

That's okay for now, but when working on different documents in different directories it is not optimal.

Thanks Idez for your support!

**Comment by ldez** [comment]
Happy if I can help you!
