### ISSUE TITLE
Is there a way to use system asciidoc, instead of bundled one?

### ISSUE THREAD

**Issue by RazrFalcon** [asciidoctor/atom-asciidoc-preview#251]
I'm using a custom extension, which is written in ruby. It there a way to use them in preview?

**Comment by Mogztter** [comment]
Hello @RazrFalcon,

Yes, there is a way!
You can cross-compile your custom extension to JavaScript using Opal: https://github.com/Mogztter/asciidoctor.js/blob/c9a047ae24803e2bcafbd162931ef8f2fa2616be/manual.adoc#how-to-compile-a-ruby-extension-to-javascript-nodejs

I don't know if it's possible to load an user's JavaScript file in Atom but if we can, you could load your custom extension.

**Comment by ldez** [comment]
Currently not.

You can transpile your Ruby code to JS with [Opal](http://opalrb.org/) but for now, it's not possible to add an user's JavaScript file in the preview.

See #127, #122, #94.
