### ISSUE TITLE
Save as HTML context menu item not working in Atom 1.24

### ISSUE THREAD

**Issue by kachkaev** [asciidoctor/atom-asciidoc-preview#258]
`Save as HTML...` context menu item seems to be broken after upgrading to Atom [1.24.0](https://github.com/atom/atom/releases/tag/v1.24.0), which was released two days ago. Clicking on this menu item displays a window to choose a file name, but then nothing happens. Strangely, there are no exceptions in Atom's console or any other signs of an error.

A shortcut for this menu item (which is `cmd+shift+s`) does not produce HTML files either – the behaviour is the same.

The issue has been confirmed on two machines where `Save as HTML...` worked in Atom 1.23.3.

- Atom version: 1.24.0
- OS: macOS High Sierra
- `asciidoc-preview` version: 2.10.3
- `language-asciidoc` version: 1.11.0

/cc @jsndyks

**Comment by ldez** [comment]
Seems to be a regression in Atom with `showSaveDialogSync`

But we have another pb:
https://github.com/atom/atom/blob/2923f0057f5acec94f638546432f50e9a027da0c/src/atom-environment.js#L1179-L1184
