### ISSUE TITLE
use another keybinding

### ISSUE THREAD

**Issue by kaystrobach** [asciidoctor/atom-asciidoc-preview#26]
```
ctrl-shift-A	editor:select-to-first-character-of-line	Core	.editor
ctrl-shift-A	asciidoc-preview:toggle	Asciidoc Preview	.workspace
ctrl-shift-A	git-plus:add	Git Plus
```

**Comment by anthonny** [comment]
Hi @kaystrobach, @YannDanthu ,

This issue should be fixed with the 0.5.0, feel free to reopen if necessary.

The new mapping is here https://github.com/asciidoctor/atom-asciidoc-preview/blob/master/keymaps/asciidoc-preview.cson
