### ISSUE TITLE
Ignoring the :toc: left option

### ISSUE THREAD

**Issue by refaelsh** [asciidoctor/atom-asciidoc-preview#262]
Hello,

It seems to be the preview is ignoring the `:toc: left` directive.
What am I missing here please?

Thanks. Refael.

**Comment by ldez** [comment]
The package support the basic [manual-placement](https://asciidoctor.org/docs/user-manual/#manual-placement) but not the [left-or-right-column-layout](https://asciidoctor.org/docs/user-manual/#left-or-right-column-layout) due to some technical constraints.

**Comment by refaelsh** [comment]
I see, so it is `normal` that the `:toc: left` directive is being ignored? Just to make sure I understand, so that the issue can be closed.

**Comment by ldez** [comment]
yes it's normal

**Comment by mojavelinux** [comment]
There's also the problem that there simply isn't enough room for a sidebar TOC in the preview (unless your monitor is enormous). It would likely fall back to the middle from hitting the breakpoint in the CSS.

I do think there's a space for an extension that provides another type of TOC for the document that's either another panel or uses the space in the preview window in another way. But I don't think it's the responsibility of the preview itself.

**Comment by refaelsh** [comment]
I don't really mind, if that is the normal behavior, then that is the normal behavior. The thing is, it took me two hours of googling and etc to understand that its probably preview's fault and not a bug in Asciidoctor. IMHO, it needs to be fixed to save others the time of trying to understand why `:toc: left` does not works.

**Comment by mojavelinux** [comment]
For example, check out https://atom.io/packages/document-outline

We could even include this in asciidoc-assistant. Open an issue there if you like the idea.

**Comment by mojavelinux** [comment]
In fact, now that I've used it, I'm convinced it should be part of asciidoc-assistant. Check it out!

![document-outline](https://user-images.githubusercontent.com/79351/37570358-862f7bec-2ab4-11e8-9d2c-e662376a1f4f.png)

**Comment by mojavelinux** [comment]
> it needs to be fixed to save others the time of trying to understand why :toc: left does not works.

It honors the request in that it shows the toc. It just can't accommodate the position request. This is the same behavior as a standalone document on a small screen. The toc always floats the top when there isn't sufficient room.

It's also documented in the user manual. See https://asciidoctor.org/docs/user-manual/#using-a-toc-with-embeddable-html I'll update it to make the emphasis even stronger.

**Comment by refaelsh** [comment]
@mojavelinux Thank you very much for your responses. I now understand. The emphasis indeed helps.
And your recommendation regarding `document-outline` is absolutely wonderful. Thank you!
I also think that it should be part of `asciidoc-assistant`.

**Comment by mojavelinux** [comment]
Great to hear!

Would you be willing to file an issue to have it added. I'll throw my support in for it.

**Comment by refaelsh** [comment]
Done! [Here](https://github.com/asciidoctor/atom-asciidoc-assistant/issues/16) it is.

**Comment by mojavelinux** [comment]
Thanks!

**Comment by refaelsh** [comment]
> It honors the request in that it shows the toc. It just can't accommodate the position request. This is the same behavior as a standalone document on a small screen. The toc always floats the top center when there isn't sufficient room.
> 

I am sorry to bother you guys again, but [here](https://www.dropbox.com/s/9msrciwjy7guds0/Untitled.png?dl=0) is a screenshot from VSCode and their AsciiDoctor preview plugin. As you can see, is shows the `toc`. On same screen, `atom-asciidoc-preview` does not shows the `toc`.

**Comment by mojavelinux** [comment]
The VSCode plugin is using a different stylesheet. That stylesheet allows the toc to be positioned on the left regardless of the width of the screen. The Atom plugin does not support this. So the behavior is intentionally different.

**Comment by refaelsh** [comment]
I see. IMHO, this would be great if it would have been supported. I will open a new issue suggesting to add this kind of functionality.

Thanks everyone.
