### ISSUE TITLE
No code-highlighting in preview window

### ISSUE THREAD

**Issue by g-uru** [asciidoctor/atom-asciidoc-preview#268]
## Description
No code-highlighting after installing the newest release.

- Atom version:
- OS: Windows 10 x64
- `asciidoc-preview` version:  2.12.0
- `language-asciidoc` version: 1.11.0

## Screenshots

![no-code-highlight](https://user-images.githubusercontent.com/22568014/39965575-2031af5e-569c-11e8-8beb-b80cc9e2cb3d.png)

## Syntax example

```adoc
[source,java]
----
public class PruefeSchaltjahr {
    public static void main(String[] args) {
        int jahr = Integer.parseInt(args[0]);
        boolean istSchaltJahr;

        istSchaltJahr = (jahr % 4 == 0);
        istSchaltJahr = istSchaltJahr && (jahr % 100 != 0);
        istSchaltJahr = istSchaltJahr || (jahr % 400 == 0);

        System.out.println(istSchaltJahr);
    }
}
----
```

**Comment by ldez** [comment]
Thanks for taking the time to open this issue.

I confirm the bug, a new version coming soon.

**Comment by g-uru** [comment]
You are welcome. Cool, thanks for letting me know :)
