### ISSUE TITLE
Preview does not work

### ISSUE THREAD

**Issue by PetrusKiendys** [asciidoctor/atom-asciidoc-preview#271]
## Description

Preview does not work, triggering preview has no effect.
A new pane is not created, it is as if nothing happened.

- Atom version: 1.26.0
- OS: Ubuntu 18.04 LTS (Bionic Beaver)
- `asciidoc-preview` version: 2.12.1
- `language-asciidoc` version: 1.11.0

**Comment by ldez** [comment]
Could you provide more information?

I don't reproduce with:
- Atom 1.26.1
- `asciidoc-preview` 2.12.1
- Ubuntu 16.04 LTS

**Comment by PetrusKiendys** [comment]
Ok, it actually works if the document that is to be previewed is correctly formatted.

However when it is not correctly formatted, the user is not presented with any form of warning or error message. I'm still getting a blank preview pane in this case, which I didn't before.

Is there any way to view a stacktrace or logging input when asciidoc-preview is activated? If there is then I can check next time this happens, I didn't see any output in the Atom console.

For now this issue can be closed, as I am not able to reproduce the bug either anymore.
