### ISSUE TITLE
Using undefined attributes in anchor id results in Uncaught Syntax Error

### ISSUE THREAD

**Issue by tylerkelly13** [asciidoctor/atom-asciidoc-preview#276]
## Description

Atom error is:
Uncaught Error: Syntax error, unrecognized expression: #anchor-id-string_{attribute}
Caused by use of undefined attribute in an anchor id. If:
- The [[asciidoc-preview]] of the page is open for a [[.adoc]] file.
- The user tries to select the heading associated with the anchor id in the editor (either using a mouse or text cursor).

The error will be thrown and the user is unable to edit the heading.
This also occurs when the attribute is defined elsewhere (such as a master document) but you are only previewing the current file.

Workaround: close the preview and retry editing the heading.

- Atom version: 1.30.0
- OS: Fedora 28
- `asciidoc-preview` version: 2.12.1
- `language-asciidoc` version: 1.11.0

## Screenshots

No screenshot. See attached Stacktrace

## Syntax example

```adoc
[id='anchor-id-string_{attribute}']
= Title of a file to be in a master file where the attribute is defined

```

## Stacktrace

[stacktrace.txt](https://github.com/asciidoctor/atom-asciidoc-preview/files/2344484/stacktrace.txt)

**Comment by mojavelinux** [comment]
This is the problematic line:

    if target = $('#' + blockId)[0]

I've run into this problem before when working with user-provided IDs. jQuery doesn't protect against an illegal ID selector. Therefore, it's necessary to use getElementById to be safe:

    if target = window.document.getElementById(blockId)
