### ISSUE TITLE
Unexpected behaviour of escaped pipe in table

### ISSUE THREAD

**Issue by hkp-wcd** [asciidoctor/atom-asciidoc-preview#287]
## Description

Escaped table separator in table cell has unexpected behaviour in preview when not at the end of a line (but works fine with Ruby asciidoctor cli html5 v1.5.7.1)

- Atom version: 1.34.0
- OS: Windows 10
- `asciidoc-preview` version: 2.12.2
- `language-asciidoc` version: 1.11.0

### Unexpected
![image](https://user-images.githubusercontent.com/42992894/54190288-d7b04900-44b3-11e9-8163-25afe3df06e5.png)
### Expected
![image](https://user-images.githubusercontent.com/42992894/54190341-edbe0980-44b3-11e9-95ea-f13fb33fc36b.png)

## Syntax example

```adoc
.Unexpected
|===
| a b \| c
|===

.Expected
|===
| a b \|
  c
|===
```

**Comment by mojavelinux** [comment]
This is a known issue in Asciidoctor.js that will be solved once it's upgraded. (It was a regular expression error that affected Asciidoctor.js / Opal).

cc: @Mogztter

**Comment by hkp-wcd** [comment]
Thanks a lot for your quick replies and overall attitude towards bug reports. Outstanding!

**Comment by mojavelinux** [comment]
:+1:

**Comment by mojavelinux** [comment]
@Mogztter What's the status on the upgrade of Asciidoctor in this plugin. Could we at least move to 1.5.8 while we're waiting for 2.0.0 to materialize? I don't really see any reason why we're sticking to 1.5.6.

**Comment by Mogztter** [comment]
@mojavelinux I think we've never took the time to upgrade but it should be pretty straightforward. I will give it a try :wink:

**Comment by mojavelinux** [comment]
Thanks @Mogztter!!
