### ISSUE TITLE
Upgrade to Asciidoctor.js 2.0

### ISSUE THREAD

**Issue by Mogztter** [asciidoctor/atom-asciidoc-preview#294]
## Description

The latest version of Asciidoctor.js contains a few bug-fixes and a lot of improvements: https://github.com/asciidoctor/asciidoctor.js/releases/tag/v2.0.3

For instance, the following issue is fixed in 2.0.3: #293

**Comment by Mogztter** [comment]
fixed in https://github.com/Mogztter/atom-asciidoc-preview/commit/e3fce00aa29a48a3f76f645caecc3da32cac717a

**Comment by mojavelinux** [comment]
Woot! Thanks you two! :beers:
