### ISSUE TITLE
Save as HTML does nothing (~/.atom/packages/asciidoc-preview/node_modules/asciidoctor.js/dist/css/asciidoctor.css not found)

### ISSUE THREAD

**Issue by sylvaticus** [asciidoctor/atom-asciidoc-preview#296]
## Description

Hello, it is a few days that when I click "Save as HTML" it asks me where to save the html, but then it does nothing, i.e. it doesn't actually save the rendered HTML. Export to PDF works.
This is independent on the specific *.adoc file I am working with

- Atom version: 1.34.0
- OS: Ubuntu Linux 18.04
- `asciidoc-preview` version: 2.13.0
- `language-asciidoc` version: 1.11.0

## Screenshots

The developer console shows an error that can't find '/home/lobianco/.atom/packages/asciidoc-preview/node_modules/asciidoctor.js/dist/css/asciidoctor.css':

![image](https://user-images.githubusercontent.com/2077159/59762313-452ffa80-9297-11e9-8a79-cc407959d8ed.png)

**Comment by ldez** [comment]
Hello, seems related to the update of Asciidoctor.js.

ping @Mogztter

**Comment by Mogztter** [comment]
Sorry I missed this reference!
The path has changed in Asciidoctor.js 2.0...
