### ISSUE TITLE
Unable to see images in project with Antora folder structure

### ISSUE THREAD

**Issue by KLynn2019** [asciidoctor/atom-asciidoc-preview#298]
## Description

Projects used with Antora have to follow a specific folder structure. With this structure, it's not necessary to include the exact path to an image in the source document. However, in order to see the image in the preview pane, I have to specify the path. Is there a way to customize the preview so that I don't have to do this?

- Atom version: 1.39.1
- OS: Windows 10
- `asciidoc-preview` version: 2.13.1
- `language-asciidoc` version: don't know...I've only been working with Asciidoc and Antora since July though

The attached zip file contains the following:

- A screenshot of the project folder structure
- A sample ADOC document
- The images referenced in the sample

[SampleFiles.zip](https://github.com/asciidoctor/atom-asciidoc-preview/files/3492540/SampleFiles.zip)

**Comment by Mogztter** [comment]
As a workaround you can define the `attachmentsdir`, `examplesdir`, `imagesdir` and `partialsdir` attributes:

![Capture d’écran 2019-08-13 à 11 32 23](https://user-images.githubusercontent.com/333276/62931365-87b91380-bdbe-11e9-8015-f4cc69a3c86c.png)

It's also possible to include the attributes in each document using the `include` directive:

![Capture d’écran 2019-08-13 à 11 34 32](https://user-images.githubusercontent.com/333276/62931361-87207d00-bdbe-11e9-8007-25eae58e7b58.png)

![Capture d’écran 2019-08-13 à 11 34 46](https://user-images.githubusercontent.com/333276/62931362-87207d00-bdbe-11e9-959d-fabc016809cd.png)


The Atom extension could potentially detect that an `antora.yml` file exists in the folder structure to automatically define these attributes.

**Comment by KLynn2019** [comment]
That did it! Thank you very much for your help.

**Comment by AndersonDev** [comment]
Any native support? [Brackets](https://github.com/asciidoctor/brackets-asciidoc-preview) supports all of this. But I like Atom more. Please add this to some config!

**Comment by Mogztter** [comment]
@AndersonDev As far as I know, you can manually configure the `imagesdir` in the preview for Adobe Brackets but it does not automatically resolve the `imagesdir` (ie. it does not automatically detect an Antora project) right ?

It's also possible to configure attributes in the settings page of this package:

![config-imagesdir](https://user-images.githubusercontent.com/333276/64557568-17ac9780-d342-11e9-9edc-95529584a4fa.png)
