### ISSUE TITLE
Asciidoc preview does not load in Atom

### ISSUE THREAD

**Issue by j-bezek-mabuhay** [asciidoctor/atom-asciidoc-preview#307]
## Description
After updating Asciidoc-preview to 2.13.1 it stopped working - cannot load a file. Previous version worked ok

- Atom version: 1.26.1
- OS: Ubuntu 18.04.4
- `asciidoc-preview` version: 2.13.1
- `language-asciidoc` version: 1.11.0

## Screenshots
![not-loading](https://user-images.githubusercontent.com/47325895/77097413-0c34da00-6a11-11ea-87d3-411fc3018afc.png)
![console](https://user-images.githubusercontent.com/47325895/77097425-1060f780-6a11-11ea-9393-abab8e44b562.png)

## Syntax example

```adoc
*mEBP - pages*
==============
:compat-mode!:
ifdef::env-github,env-browser[:outfilesuffix: .adoc]
:appendix-caption: Appx
:toc: left
:toclevels: 4
:sectnums:
:imagesdir: images/
:y: &#10003;

[[mEBPPages]]

toc::[]

== Navigation and Flows
=== Bottom navigation bar
A bottom navigation bar is a central point to quickly access different areas within the application.
```

**Comment by ldez** [comment]
Hello,

could you update Atom to more recent version?

**Comment by j-bezek-mabuhay** [comment]
1,45.0 x64 - issue resolved, asciidoc-preview loads. Please close the issu.
Sorry, I have not realized Atom is not update. Thanks!
