### ISSUE TITLE
Add autocomplete of attribute references in editor pane

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/atom-asciidoc-preview#34]
When editing AsciiDoc, it would be incredibly useful to have autocomplete support for attribute names when entering an attribute reference. This would work much like autocomplete works in IDEs when entering a variable or method name.

In the editor pane, I would type `{`, then press `<Ctrl><Space>`. That would bring up a drop down list of names that would be filtered as I type additional characters. If I select one of the names, it would be inserted into the document after the `{` and then a `}` would be automatically added after the name.

The list of attribute names can be retrieved from the `Document#attributes` map. We'd need to do a bit more work to get attributes defined in the flow of the document...but let's not worry about those in the initial prototype.

**Comment by Mogztter** [comment]
@mojavelinux I think we can close this issue and open another one for autocompletion on document attributes no ?

**Comment by mojavelinux** [comment]
Yes. I think the improvements I'd like to see are well covered by #130 and #131.
