### ISSUE TITLE
Keyboard inline macro's not enabled

### ISSUE THREAD

**Issue by ghost** [asciidoctor/atom-asciidoc-preview#35]
Syntax picks up (highlighting) but the live preview doesn't

![image](https://cloud.githubusercontent.com/assets/6564110/3911221/56b1ba42-231f-11e4-8de2-806f29e6cc41.png)

**Comment by gavenkoa** [comment]
@mojavelinux Hasn't `:macros: ui` or  `:macros: kbd`  syntax been implemented yet?

With v1.5.7 I can enable `kbd` with `:experimental:`. Any other direct method to enable only `kbd`?

**Comment by mojavelinux** [comment]
The experimental attribute is still the way to enable them.
