### ISSUE TITLE
Update Package To Use New autocomplete-plus API

### ISSUE THREAD

**Issue by joefitzgerald** [asciidoctor/atom-asciidoc-preview#45]
Please:

* Don't depend on autocomplete-plus in your package.json
* Switch to using an editor instead of an editorView during registration

Updated example: https://github.com/atom-community/autocomplete-plus/wiki/Tutorial:-Registering-and-creating-a-suggestion-provider

**Comment by anthonny** [comment]
The changes are minor but it is always enriching to have the point of view of others, if you have a moment to make a fast review it would be cool :smile:
