### ISSUE TITLE
unable to install asciidoc-preview package

### ISSUE THREAD

**Issue by bgruenefeld** [asciidoctor/atom-asciidoc-preview#50]
i was trying to install asciidoc-preview on my windows machine with:

apm install asciidoc-preview

which results in the following error:

npm http 304 https://registry.npmjs.org/core-util-is
npm ERR! git clone git://github.com/anthonny/opal-npm-wrapper.git Cloning into bare repository 'C:\Users\gruenefeld\.atom\.node-gyp\.atom\.apm\_git-remotes\git-github-com-anthonny-opal-npm-wrapper-git-10c5b7b0'...
npm ERR! git clone git://github.com/anthonny/opal-npm-wrapper.git fatal: unable to connect to github.com:
npm ERR! git clone git://github.com/anthonny/opal-npm-wrapper.git github.com[0: 192.30.252.128]: errno=No error
npm ERR! Error: Command failed: Cloning into bare repository 'C:\Users\gruenefeld\.atom\.node-gyp\.atom\.apm\_git-remotes\git-github-com-anthonny-opal-npm-wrapper-git-10c5b7b0'...
npm ERR! fatal: unable to connect to github.com:
npm ERR! github.com[0: 192.30.252.128]: errno=No error
npm ERR!
npm ERR!
npm ERR!     at ChildProcess.exithandler (child_process.js:658:15)
npm ERR!     at ChildProcess.emit (events.js:98:17)
npm ERR!     at maybeClose (child_process.js:766:16)
npm ERR!     at Process.ChildProcess._handle.onexit (child_process.js:833:5)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "c:\\Users\\gruenefeld\\AppData\\Local\\atom\\app-0.174.0\\resources\\app\\apm\\node_modules\\atom-package-manager\\bin\\node.exe" "c:\\Users\\gruenefeld\\AppData\\Local\\atom\\app-0.174.0\\resources\\app\\ap
m\\node_modules\\atom-package-manager\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "c:\\Users\\gruenefeld\\AppData\\Local\\atom\\app-0.174.0\\resources\\app\\apm\\node_modules\\atom-package-manager\\.apmrc" "--userco
nfig" "C:\\Users\\gruenefeld\\.atom\\.apmrc" "install" "C:\\Users\\gruenefeld\\.atom\\.node-gyp\\.atom\\.apm\\asciidoc-preview\\0.4.2\\package.tgz" "--target=0.20.0" "--arch=ia32"
npm ERR! cwd C:\Users\GRUENE~1\AppData\Local\Temp\apm-install-dir-115021-5512-14r6f60
npm ERR! node -v v0.10.35
npm ERR! npm -v 1.4.4
npm ERR! code 128
npm

i got the same error on an linux machine.
I already change my git config with:

git config --global url."https://github.com/".insteadOf git@github.com:
git config --global url."https://".insteadOf git://

but with no success.
Any ideas whats going wrong?

Kind regard
Bernd

**Comment by bgruenefeld** [comment]
git config --global url."https://github.com/".insteadOf git@github.com:
git config --global url."https://".insteadOf git:// 

but with no success. 
Any ideas whats going wrong?

Kind regard
Bernd

**Comment by anthonny** [comment]
Hi @bgruenefeld !

By reading that, I think of a network problem :
```
npm ERR! fatal: unable to connect to github.com:
npm ERR! github.com[0: 192.30.252.128]: errno=No error
```
Can you try to ping github.com ?

**Comment by anthonny** [comment]
Have you a proxy ? maybe the protocole `git://` is blocked

**Comment by bgruenefeld** [comment]
ping github.com 

... works fine.
I´m also able to clone the repository from github via ssh

**Comment by anthonny** [comment]
If you are behind a proxy, i think your problem is the same than :
https://github.com/atom/atom/issues/2309

I have a workaround :

1- Close atom
2- Go into your ~/.atom folder
3- run `git clone https://github.com/asciidoctor/atom-asciidoc-preview.git asciidoc-preview`
4- `cd asciidoc-preview`
5- `git checkout v0.4.2`
6- run `npm install`

It's certainly not a good solution ...

I fixed the `package.json` and change the dependency to `opal-npm-wrapper` :
https://github.com/asciidoctor/asciidoctor.js/commit/143a6867a6599fe6b4f3344d332ba650db4ccd66#diff-b9cfc7f2cdf78a7f4b91a753d10865a2

Should be ok in the next version.

**Comment by bgruenefeld** [comment]
thanks a lot for the very quick support - excellent!! :-)

i made the steps you suggested.
Additionaly i copied the asciidoc-preview folder in the ~/.atom/package folder

now it works.

**Comment by anthonny** [comment]
> thanks a lot for the very quick support - excellent!! :-)

Thanks for filing the issue :smile: 

:beers: 
I am glad that all is ok for you now.
I updated my previous comment and added the `packages` folder.

**Comment by ctruta** [comment]
I had trouble installing this package also. I had to move away from the firewall.
When installing from github, the trick is to use the https:// protocol, not the git:// protocol.
