### ISSUE TITLE
Using + for syntax highlighting doesn't render in Atom Preview

### ISSUE THREAD

**Issue by jaredmorgs** [asciidoctor/atom-asciidoc-preview#53]
I was editing the jekyll-asciidoc-quickstart Readme.adoc file in Atom, and noticed that when I surrounded a command in the + delimiters, the code did not get formatted.

![atom_asciidoc_render](https://cloud.githubusercontent.com/assets/952793/5994375/8554bed8-aabc-11e4-8a44-9957e0b452f9.png)

If I fenced it with back-ticks, it worked.

![atom_fence_code](https://cloud.githubusercontent.com/assets/952793/5994392/293dcc4c-aabd-11e4-8c10-cb693c8b4cb4.png)

I've adopted a fencing approach in this file just so it renders in the short term, because I'm relying on the live render to tell me if I have made an error with markup (not staging these files locally first) as I get used to AsciiDoc authoring.

If I've misunderstood anything with regard to usage, I apologise, and this issue can be insta-closed. :smiley:

**Comment by mojavelinux** [comment]
As far as i can tell, there is no need for the `+` lines in this case. A `+` line is used to string together multiple blocks as part of the same list item. I don't see a list here, therefore there's no need for them. You can just take them out.

```
For yum-based package managers, the command to run is:

 $ sudo yum install ruby rubygems
```

**Comment by jaredmorgs** [comment]
Yeah, sorry Dan. I just realised this after @jirutka gave me some AsciiDoc
syntax advice. I'll get there eventually. ;)

**Comment by mojavelinux** [comment]
:+1:

**Comment by jaredmorgs** [comment]
All good to close. Thanks for making this plug-in for Atom. It's awesome!
