### ISSUE TITLE
Turning auto-numbering off

### ISSUE THREAD

**Issue by jxxcarlson** [asciidoctor/atom-asciidoc-preview#58]
Placing `:numbered!:` at the top of the file does not turn auto-numbering of sections off.

PS.  Atom-asciidoc-preview rocks!  I use it  every day!!

**Comment by mojavelinux** [comment]
I think it has to be controlled via the UI options atm. Right click on the preview to see the options.

**Comment by ldez** [comment]
![capture du 2016-06-01 00-12-32](https://cloud.githubusercontent.com/assets/5674651/15692238/9c201b86-278d-11e6-9f53-46debbe068ef.png)

**Comment by mojavelinux** [comment]
The only problem about these boolean options is that technically, all options have three states.

* Always on (-a sectnums)
* Always off (-a sectnums!)
* Let the document decide

You could actually consider a fourth state, which is "soft on":

* Turn it on unless the document turns it off (-a sectnums@)

So we might have to rethink the options page.

**Comment by mojavelinux** [comment]
Please note that "numbered" is the old name for this switch and should no longer be used.

**Comment by ldez** [comment]
I going to change the option
