### ISSUE TITLE
Fails to load in Atom 0.182.0

### ISSUE THREAD

**Issue by j-manu** [asciidoctor/atom-asciidoc-preview#63]
The package fails to load with an error message
```
Failed to activate package named 'asciidoc-preview' Error: Cannot find module '/Applications/Atom.app/Contents/Resources/app/node_modules/markdown-preview/node_modules/highlights'
```

I found `highlights` in _Applications/Atom.app/Contents/Resources/app/node_modules/_ but changing
```js
Highlights = require path.join(pathWatcherDirectory, 'node_modules', 'highlights')
```

in `lib/renderer.coffee` to just 
```js
Highlights = require 'highlights'
```
did not work. But changing it to this worked.
```js
Highlights = require path.join(pathWatcherDirectory, '../', 'highlights')
```

I thought just `require 'highlights'` should works since `require 'cheerio'` and `require 'underscore-plus'` works but I know nothing about how node or atom work :). Is it because you are not including _highlights_ in package.json ? Shouldn't it be included since it is a dependency?

**Comment by anthonny** [comment]
Thank you for having filled this issue :+1:, it should be fixed with 0.4.3
I have no direct dependence with Highlight because it requires a compilation

**Comment by j-manu** [comment]
Highlights is now inside the global modules directory and not inside
markdown preview.

So even if the dependency is declared Atom will reuse the highlights
already installed which will involve no compilation ?

**Comment by royemmerich** [comment]
:+1:

Yay, it works! Thanks guys.

**Comment by S0lll0s** [comment]
Close this then...
