### ISSUE TITLE
Smart quotes not properly previewed

### ISSUE THREAD

**Issue by rocketraman** [asciidoctor/atom-asciidoc-preview#66]
Smart quotes are not properly previewed. The output text is monospaced using the semantics of the back-tick symbol, and the quotes remain as simple rather than curved marks.

Input text that looks like this:

```
Here's how you say "`Hello, World!`" in Ruby.
```

is rendered like this:

![smart-quotes-bad](https://cloud.githubusercontent.com/assets/53049/6586918/64b7d3cc-c754-11e4-98d3-a2dcf3a701c6.png)

but it should be rendered like this:

![smart-quotes-good](https://cloud.githubusercontent.com/assets/53049/6586938/9a651282-c754-11e4-9255-6d21f29212b5.png)

**Comment by mojavelinux** [comment]
There's two reasons this might be happening:

1. The document has the `compat-mode` attribute set.
2. You are using an older version of Asciidoctor (perhaps an old version of the plugin)

You can check the version of Asciidoctor by referencing the `asciidoctor-version` attribute anywhere in the document.

```
{asciidoctor-version}
```

If that reports 1.5.0 or greater, then I'd check the `compat-mode` attribute.

```
ifdef::compat-mode[compat mode is on!]
```

Let us know what you find.

**Comment by rocketraman** [comment]
It seems to have fixed itself after a restart. Thanks for the debugging tips.

**Comment by mojavelinux** [comment]
:+1:

**Comment by anthonny** [comment]
Thank you Dan!

Le mar. 17 mars 2015 23:21, Dan Allen <notifications@github.com> a écrit :

[image: :+1:]
