### ISSUE TITLE
Status bar element doesn't play well

### ISSUE THREAD

**Issue by lee-dohm** [asciidoctor/atom-asciidoc-preview#67]
![screen shot 2015-03-12 at 7 28 33 am](https://cloud.githubusercontent.com/assets/1038121/6619744/8de34fa2-c889-11e4-9350-93a74421d61e.png)

All the other status bar elements are `div`s and this one is a `span`, among other differences.

![screen shot 2015-03-12 at 7 32 33 am](https://cloud.githubusercontent.com/assets/1038121/6619821/1ad3036c-c88a-11e4-8e08-d757a5ac1f67.png)

**Comment by anthonny** [comment]
Hi @lee-dohm,

Thank you :+1: , i'll work on this problem asap

**Comment by lee-dohm** [comment]
You're welcome! Feel free to take a look at my status bar indicator packages, [soft-wrap-indicator](https://atom.io/packages/soft-wrap-indicator) and [indentation-indicator](https://atom.io/packages/indentation-indicator) for reference.

**Comment by anthonny** [comment]
@lee-dohm, this issue should be fixed with the 0.5.0, feel free to reopen if necessary
