### ISSUE TITLE
Status bar element doesn't display on startup

### ISSUE THREAD

**Issue by lee-dohm** [asciidoctor/atom-asciidoc-preview#68]
## Repro Steps

1. Launch Atom
1. Open an ASCIIDoc file
1. While leaving the ASCIIDoc file open, close Atom using <kbd>Cmd+Q</kbd>
1. Launch Atom again

**Expected:** Status bar element to display
**Actual:** Status bar element does not show until changing to another tab and changing back

**Comment by ldez** [comment]
Status bar display will be remove on 2.2.0
