### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by borisovg** [asciidoctor/atom-asciidoc-preview#69]
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (/usr/share/atom/resources/app/src/atom.js:54:11)
HTMLAnchorElement.<anonymous> (/home/borisov/.atom/packages/asciidoc-preview/lib/asciidoc-preview-view.coffee:276:35)
```

**Comment by anthonny** [comment]
Hi @borisovg,

This issue should be fixed with the 0.5.0, feel free to reopen if necessary
