### ISSUE TITLE
Add option to sync scroll of editor and preview

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/atom-asciidoc-preview#82]
It would be nice to have an option that syncs the scroll of the editor and the preview. You can see an example of the feature in the following video from Beegit.

http://blog.beegit.com/new_features/2015/04/29/scroll-sync-release/

We can likely use the AST to figure out what part of the preview aligns with the source and update the scroll offset accordingly. I don't expect that it would be a smooth scroll (like in the video), just that the preview is showing the content that corresponds to what is visible in the editor.

**Comment by yfain** [comment]
Yes, this would be a very useful feature.

**Comment by anthonny** [comment]
I agree :+1:

**Comment by livejoe** [comment]
This would be a nice feature. Having come to asciidoc via markdown, where sync scroll can be found in various editors, I miss the ability to sync scroll the preview pane when I want to get a quick view how things are looking.

**Comment by flyisland** [comment]
+1

**Comment by JohnLukeBentley** [comment]
A temporary workaround is to use the http://asciidocfx.com/ editor, which has autoscrolling out of the box.

**Comment by mojavelinux** [comment]
The extension for Brackets also has this feature.

The good news for this package is that the same problem has been solved using the same technologies in other IDEs. At the very least, that means it's just a matter of porting that logic to this package.

**Comment by JohnLukeBentley** [comment]
Yes other IDEs show that it can be done, which eases the way for this package.

One thing I don't like about sync scrolling with the other IDEs I've used is that it all occurs in one big window (with split panes). I'd like to have a separate window for sync scrolling (and previewing more generally), to put on my second monitor.

I'm not sure if there's any fundamental blockers to achieving that functionality (e.g. due to the Windows OS not facilitating communicating doc positions between windows).

**Comment by mojavelinux** [comment]
> I'd like to have a separate window for sync scrolling

My understanding was that Brackets supports this mode. That needs to be verified though.

**Comment by lucascosti** [comment]
Yes please! This would make my life a lot easier, and is something a Brackets-loving associate never fails to remind me over using Atom :)

**Comment by Mogztter** [comment]
@ldez Want to give it a try ?
Here's a quick and dirty implementation: https://github.com/Mogztter/asciidoctor-fast-live-reload

**Comment by ldez** [comment]
@Mogztter yes it's in my roadmap :wink:

**Comment by igagis** [comment]
Would be also nice to place the cursor caret to the right place in source when clicked on preview element

**Comment by nerk** [comment]
For the Brackets extension I used the mechanism from Asciidoc FX. It uses an Asciidoctor extension to add a 'data-line' attribute to each generated HTML block containing the corresponding source line number (see https://github.com/asciidoctor/brackets-asciidoc-preview/blob/master/lib/data-line-extension.js). With this in place, it is very simple to synchronize editor with preview pane. The Brackets extension can synchronize in both directions and also supports a detached preview window mode. Should not be to difficult to implement this for Atom.

**Comment by Mogztter** [comment]
I think both approaches are equivalent because the extension is also using `lineno` on Block.
But adding an attribute might be better than generating a unique id (if the HTML element does not have one).

**Comment by mojavelinux** [comment]
We went with the auto-generated ID approach. That required the least amount of change atm. However, it's easy to revisit in the future.

**Comment by mojavelinux** [comment]
And we're live! :tada: 

Thanks @Mogztter and @ldez !!

**Comment by lucascosti** [comment]
Thanks for the hard work, everyone! 🎆  It's a great first step. Other than syncing on scroll (rather than clicking in the source), I have one other suggestion, but I'll open a new issue for that.

**Comment by mojavelinux** [comment]
I filed #221 to sync on scroll.

However, as I thought about this behavior, it became clear to me that syncing with the scroll position isn't always the desired behavior. Sometimes, and for some people, syncing with the cursor is more natural. So this needs to be a preference, which I suggested in the issue.

**Comment by astubbs** [comment]
Is it possible to set the vertical location of the preview pane? Atm it seems to scroll to the top of the pane by default - it would be nice to match the cursor position in the source pane. (i.e. my change that is entered in the editor, is at the top of the preview pane)
