### ISSUE TITLE
Explain the role of safe mode in the README

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/atom-asciidoc-preview#87]
Add a brief explanation to the purpose of the safe mode setting in the README. Point to the section in the Asciidoctor user manual for more information. In particular, we want to emphasize that this setting controls whether includes work or not.

http://asciidoctor.org/docs/user-manual/#running-asciidoctor-securely

**Comment by ldez** [comment]
the safe-mode is now explains in the settings: #153
