### ISSUE TITLE
Support without Asciidoctor

### ISSUE THREAD

**Issue by jeffeb3** [asciidoctor/atom-asciidoc-preview#92]
I don't have Asciidoctor, but I do have Asciidoc. 

Maybe you could change the interface to allow people to use asciidoc instead?

I managed to get this to work by changing the command to:
asciidoc -b html5 -d book -a lang=ja -o {{{tempHTMLPath}}} {{{tempSourcePath}}}

This should at least be documented, although I think it would make more sense as a well defined option in the settings. Maybe the command line option should be [Asciidoctor defaults, Asciidoc defaults, custom (with box)]

**Comment by mojavelinux** [comment]
I am strongly opposed to this idea. I do not want to encourage people to use AsciiDoc Python. It is a legacy implementation, it is buggy, it is slow and it is insecure. Of course, I love the language that AsciiDoc Python gave us, and I'll always appreciate the role it played in history, but I don't want it to be part of the Asciidoctor project.

I'm really confused why you want to use it anyway. Is there some feature of AsciiDoc Python you must have that you can't get with Asciidoctor? If so, I'd rather address that issue.

**Comment by jeffeb3** [comment]
It's available in red hat

**Comment by mojavelinux** [comment]
Asciidoctor is also available in Red Hat (RHEL). It's built for EPEL <https://admin.fedoraproject.org/pkgdb/package/rubygem-asciidoctor/> and should be available in the repository. If it's not there, we need to figure out why it's stuck.

You also have the option of building your own RPM <https://github.com/asciidoctor/rubygem-asciidoctor-rpm>.

**Comment by jeffeb3** [comment]
Well, I sort of just fell into this, and I'm unprepared for arguments about which is better. I just found AsciiDoc today, and I like your preview package. I just want them to work together so I can see how much use I'll get out of this. asciidoc.py is also in the main RHEL 7 repos, not just in EPEL. Also, for RHEL 7, I don't see asciidoctor in RHEL or EPEL 7, so that's really the nail in the coffin for me.

I assumed that you'd want to make your package more flexible, but if you're trying to discourage use of asciidoc.py, then I can see why you wouldn't want to help people use it with your package. Lucky for me, you did expose the command, so I was able to make it work with the tool I have.

**Comment by mojavelinux** [comment]
@jeffeb3, I do understand where you're coming from, and we want to make that path easy. Trust me. I just don't think we want to do it by stepping backwards, but rather forwards.

I'm going to look into why Asciidoctor isn't in RHEL 7. Something has gotten hung up. It's already approved for EPEL, though I think it should be in the main repo (esp given that Red Hat itself uses it).

Having said that, I'm still confused about something. This extension, for the Atom text editor, uses a bundled version of Asciidoctor.js, so you don't even need AsciiDoc on your system to use it. Are you sure you aren't talking about a different program? Could you clarify which tool you are using to plug in AsciiDoc Python and where?

**Comment by jeffeb3** [comment]
I am sorry!

I have asciidoctor-preview installed in atom, made by griffin-stewie. So this enhancement is in the wrong place.
