### ISSUE TITLE
Images do not refresh.

### ISSUE THREAD

**Issue by asmyers** [asciidoctor/atom-asciidoc-preview#95]
When including images in an asciidoc document they do not get refreshed when the
document is updated.  Even if I close the tab showing the preview and reopen it the old
images are still displayed.

**Comment by mojavelinux** [comment]
My first thought is whether this is an issue in Atom. We could always append a query string to the images using JavaScript to force them to reload...perhaps when the tab is opened.

**Comment by sandermak** [comment]
Running into the same issue currently; is there anything I can do to work around this problem?

**Comment by jxerome** [comment]
I have the same issue and this is quite annoying.

**Comment by mojavelinux** [comment]
Does the same thing happen in the Markdown preview by chance?

**Comment by nicorikken** [comment]
Can confirm as well. A restart of Atom is needed to refresh the image. Simply toggling the preview is not enough. I've tried it with the markdown preview, and it shows the same behavior.

**Comment by mojavelinux** [comment]
Perhaps we can append a timestamp to the query string of the image URL. Not pretty, but if this is a low-level issue in Atom, that might allow us to work around it.

**Comment by nicorikken** [comment]
Any idea if this would impact other forms of caching/optimization by Atom? Maybe a hash would be better (more computing though)? If the time-stamp is only updated when the plugin is toggled, I guess it should work, rather than continuously updating cached images when the preview reloads.

**Comment by mojavelinux** [comment]
Can we find the upstream bug?

**Comment by ldez** [comment]
It's not a bug but a feature ;)
Use to optimize Atom interface.

**Comment by sandermak** [comment]
Looks like adding a querystring/fragment is what the Markdown guys did as well: https://github.com/Galadirith/markdown-preview-plus/issues/49

**Comment by ldez** [comment]
I have created a PR with this trick but currently the images don't reload only when they change.
It's normal.

To do automatically refresh when changed we must watch the images. Related to #136.

**Comment by nicorikken** [comment]
@ldez does your PR trigger continuous reloading, or on toggle? The latter would be sufficient for now as it prevents having to close Atom. Better file watching like #136 would indeed be nice.

**Comment by ldez** [comment]
> your PR trigger continuous reloading, or on toggle

Both, if you change the document images are automatically reload, if you only change image you must toggle.
