### ISSUE TITLE
Attribute :data-uri: causes asciidoc-preview to hang

### ISSUE THREAD

**Issue by adam820** [asciidoctor/atom-asciidoc-preview#97]
Hi,

Including the `data-uri` attribute in the document itself causes the asciidoc-preview window to not successfully load/render, looping forever on:

![image](https://cloud.githubusercontent.com/assets/1794794/8163352/7f0f82f4-1350-11e5-9d06-10a6b11a9beb.png)

If a document was already rendered, and then the attribute added in, the page never refreshes, which could be confusing.

Versions:
asciidoc-preview 0.5.1
atom 0.209.0

**Comment by mojavelinux** [comment]
I wonder if we should forcefully disable the data-uri attribute in this environment. That would be a matter of undefining the attribute in the attribute list passed to the processor.

**Comment by adam820** [comment]
Would there ever be a situation where, when doing a live-preview in-editor, you wouldn't have access to the imagesdir and a linked image? As far as I can surmise, you'd need it to begin with, for the embedding, so it almost seems circular.

**Comment by mojavelinux** [comment]
My point is that I don't think embedding makes sense for the preview. The embedding feature is for exporting the HTML as a single bundle. That's not necessary for the preview and its better (and faster) to allow the browser component to locate and render the image.

There's also the potential problem that JavaScript is not reading the images correctly in binary format. I can't say I've ever verified the IO capabilities in the way we are retrieving files. I suppose if the Atom preview is using the node environment, perhaps we are using the node IO, but again, I've never verified that so I can't say one way or another.

**Comment by akhayyat** [comment]
I'm hitting this issue too. Any action taken to fix it yet?

**Comment by mojavelinux** [comment]
As a quick fix, you should be able to add `data-uri!` to the attributes list in the configuration and it will disable this attribute for all attributes in the Atom preview. We are just talking about making this the default.

**Comment by akhayyat** [comment]
Great! Amm.. How can I add an attribute to the configuration?

**Comment by mojavelinux** [comment]
When you are looking at the package in the packages list, click on Settings. Then, add `data-uri!` to the end of the "Default Attributes" field (be sure to separate it from the other text by at least one space). The value should look like:

```
platform=opal platform-opal env=browser env-browser source-highlighter=highlight.js data-uri!
```

**Comment by mojavelinux** [comment]
Note that these values override anything that's set in the document (unless the value ends in a `@`, in which case the attribute in the document wins).

**Comment by akhayyat** [comment]
1. I can't append a new attribute to the default attributes (unless the default attributes are always applied even without appearing in the default attribute field). The default attributes are only shown when the field is empty. I realize this is an Atom issue, but I wasn't sure whether typing something in would override the defaults or append to them.

2. Is there any use case for *not* including the `data-uri!` attribute by default?

**Comment by mojavelinux** [comment]
Ah. I realized I must have already typed those values manually on my
machine. Reenter the values you see, then add data-uri.

data-uri is for publishing, so it's not needed in a preview tool.

**Comment by akhayyat** [comment]
> data-uri is for publishing, so it's not needed in a preview tool.

Hence my earlier question:
> Is there any use case for *not* including the `data-uri!` attribute by default?

IOW, are there any arguments against including it in the default attributes of the preview package? Why not just do it?

**Comment by mojavelinux** [comment]
Yes, we should add it to the default list. That's the solution to this
issue. Now we just need a pull request.

**Comment by akhayyat** [comment]
Can we get a release that includes this fix?

**Comment by anthonny** [comment]
Sure, i'll make it in 4 hours at lunch :smile:

**Comment by akhayyat** [comment]
Cool! Sounds like a delicious lunch ;)

**Comment by mojavelinux** [comment]
Releases always make lunch delicious!

**Comment by anthonny** [comment]
Done! :beers: 
Feel free to close the issue if all is ok for you :smile:

**Comment by abelsromero** [comment]
:tada:

**Comment by Mogztter** [comment]
Resolved in https://github.com/asciidoctor/atom-asciidoc-preview/pull/98
